#!/bin/bash

# exit on error
set -e

source /data/opkg-helpers/opkg-common.sh

PACKAGENAME=mount-shares

NEW_FILE=/lib/libcap-ng.so.0.0.0
LNK_FILE=/lib/libcap-ng.so.0
TMP_FOLDER=/tmp/mount-shares
TMP_FILE=${TMP_FOLDER}/libcap-ng.so.0.0.0

if [[ -f ${NEW_FILE} ]]; then
  echo "backing up existing file ${NEW_FILE} to ${NEW_FILE}.bak"
  mv ${NEW_FILE} ${NEW_FILE}.bak
fi

echo "copying ${TMP_FILE} to ${NEW_FILE}"
cp ${TMP_FILE} ${NEW_FILE}
chmod +x ${NEW_FILE}

echo "unlinking"
unlink ${LNK_FILE} 2>/dev/null || true

echo "Creating missing symbolic link ${LNK_FILE} --> ${NEW_FILE}"
ln -s ${NEW_FILE} ${LNK_FILE}

echo "cleaning up"
rm -r ${TMP_FOLDER}

add_package_name_to_custom_packages_file "${PACKAGENAME}"

echo "successfully installed ${PACKAGENAME}"

