#!/bin/bash

# exit on error
set -e
source /data/opkg-helpers/opkg-common.sh

PACKAGENAME=mount-shares
NEW_FILE=/lib/libcap-ng.so.0.0.0

if [[ -f $NEW_FILE.bak ]]; then
  echo "restoring $NEW_FILE.bak to $NEW_FILE"
  mv $NEW_FILE.bak $NEW_FILE
fi

remove_package_name_from_custom_packages_file "${PACKAGENAME}"

echo "successfully removed ${PACKAGENAME}"

