#!/bin/bash

package_name="mount-shares"
new_file=/lib/libcap-ng.so.0.0.0

if [[ -f $new_file.bak ]]; then
  echo "restoring $new_file.mountshares to $new_file"
  mv $new_file.mountshares $new_file
fi

source "${VE_ROOT_DIR:-}/data/opkg-helpers/opkg-common"
opkg_common_unregister_package "${package_name}"

echo "successfully removed ${package_name}"

