#!/usr/bin/env bash

RESTART_GUI_SERVICE=1
DBUS_SETTINGS="
	  Themer/Theme:s:0:0:'Dark'
		Themer/Dark/TextColor:s:0:0:'#ffffff'
		Themer/Dark/WindowBackgroundColor:s:0:0:'#202020'
		Themer/Dark/BackgroundColor:s:0:0:'transparent'
		Themer/Dark/BackgroundColorSelected:s:0:0:'#4790d0'
		Themer/Dark/BackgroundColor2:s:0:0:'#313131'
		Themer/Dark/IconSuffixNormal:s:0:0:'-active'
		Themer/Dark/IconSuffixSelected:s:0:0:'-active'
		Themer/Dark/BorderColor:s:0:0:'#3c3c3c'
		Themer/Dark/ServiceBackgroundColor:s:0:0:'#b07c04'
		Themer/Dark/BackgroundColorSelected:s:0:0:'#2969a1'
		Themer/Dark/BackgroundTankColor:s:0:0:'#cccccc'

		OpkgManager/CustomMenus/PageSettingsDisplay/ThemerPageSettingsSubMenu:s:0:0:
"
#DBUS_SETTINGS_DEPRECIATED=""

if [[ "$1" == "dev-install" ]]; then
  VE_ROOT_DIR=/data/dev/utils/opkg-manager/src
fi

source ${VE_ROOT_DIR:-}/data/opkg-manager/install-helper

if [[ "$1" == "install" || "$1" == "post-install" || "$1" == "dev-install" ]]; then
	install_helper_post_install
 
elif [[ "$1" == "remove" || "$1" == "post-remove" ]]; then
	install_helper_pre_remove
 
else
	echo args are 'install/post-install' or 'remove/pre-remove'
  exit 1
fi

# install_helper_finished
 
#__add_remove_dbus_settings 0
#install_helper_post_install
#themer_common_patch_files
#themer_common_remove_patch_from_files
#themer_common_add_remove_dbus_settings 1
