#!/bin/bash

set -o nounset

#compiler_script=~/dev-local/gui-v2/tools/gui-v2-plugin-compiler.py
compiler_script=../../../../../../tooling/gui-v2-plugin-compiler.py

if [[ ! -f "$compiler_script" ]]; then
  echo "/opt/victronenergy/gui-v2/gui-v2-plugin-compiler.py not found" >&2
  exit 1
fi

PLUGIN_NAME=Inetbox
MINIFY="--minify"
#PRE_COMPILE="--pre-compile"
PLUGIN_VERSION=$(cat version 2>/dev/null || echo v1.0.0);
PLUGIN_VERSION=$(echo "${PLUGIN_VERSION%.*}.$((${PLUGIN_VERSION##*.}+1))" | tee version)
[[ -n ${PRE_COMPILE:-} ]] && MINIFY=

declare DEVICE_IP_ADDRESS="${1:-}"
# Force Qt6 tools to avoid qtchooser wrappers (/usr/bin/lupdate, /usr/bin/rcc).
export PATH="/usr/lib/qt6/bin:/usr/lib/qt6/libexec:${PATH}"

# force delete so file size reporting is not using cache (when mounting/zfs etc)
rm -f ./output/${PLUGIN_NAME}.json

python3 "$compiler_script" \
    --name ${PLUGIN_NAME} \
		--version ${PLUGIN_VERSION} \
    --min-required-version v1.2.13 \
    --settings InetboxPageSettings.qml ${MINIFY:-} ${PRE_COMPILE:-}

#--devicelist 0xD01A Inetbox_devicelist_main.qml inetbox_page_title_simple

if [[ -n "${DEVICE_IP_ADDRESS}" ]]; then
  echo "--- copying plugin to device ${DEVICE_IP_ADDRESS}"
  scp "./output/${PLUGIN_NAME}.json" "root@${DEVICE_IP_ADDRESS}:/tmp/${PLUGIN_NAME}.json"
  ssh root@"${DEVICE_IP_ADDRESS}" 'bash -s' << EOF
mkdir -p "/data/apps/available/${PLUGIN_NAME}/gui-v2" && \
cp "/tmp/${PLUGIN_NAME}.json" "/data/apps/available/${PLUGIN_NAME}/gui-v2/${PLUGIN_NAME}.json"
mkdir -p /data/apps/enabled && \
ln -sf "/data/apps/available/${PLUGIN_NAME}" /data/apps/enabled

svc -t /service/flashmq

rm -f /tmp/${PLUGIN_NAME}.json
EOF

fi

mkdir -p ../../../../src/data/apps/available/${PLUGIN_NAME}/gui-v2

cp ./output/${PLUGIN_NAME}.json \
		../../../../src/data/apps/available/${PLUGIN_NAME}/gui-v2/${PLUGIN_NAME}.json

declare human;human="$(du -h "./output/${PLUGIN_NAME}.json" | awk '{print $1}')"
declare bytes;bytes="$(wc -c < "./output/${PLUGIN_NAME}.json")"
echo "  Options: ${MINIFY:-} ${PRE_COMPILE:-}"
echo "  Version: ${PLUGIN_VERSION}"
echo "  Size: ${human} (${bytes})"