#!/bin/bash

expand_root_fs() {
  # Expand rootfs and make it writable
  /opt/victronenergy/swupdate-scripts/resize2fs.sh
}

is_root_fs_readonly() {
 V=$(grep "[[:space:]]ro[[:space:],]" /proc/mounts)
 if [ -z "${V}" ] ; then
   IS_FS_READONLY=false
 else
   IS_FS_READONLY=true
 fi
}

mount_root_fs_readwrite() {
  echo "mounting fs as read write" >> ${LOG}
  mount -o remount,rw /
}

mount_root_fs_readonly() {
  echo "mounting fs as readonly" >> ${LOG}
  mount -o remount,ro /
}

ensure_feed() {
  FEED_CONFIG_FILE="/etc/opkg/thespinmaster.conf"
  if [ ! -f $FEED_CONFIG_FILE ]; then
    echo "adding opkg feed" >> ${LOG}
    FEED_URL="https://github.com/thespinmaster/venus-os/raw/refs/heads/main/feed"
    echo "src/gz thespinmaster ${FEED_URL}" > "${FEED_CONFIG_FILE}" 
  fi
  opkg update
}

LOG=/data/test-install/log
rm ${LOG}

echo "${1}" >> ${LOG}
echo " $(date)"

# get the ipk name from the dir name this script
# is located in
IPK=$(basename "$(dirname "$(realpath "${0}")")")
echo "name:${IPK}" >> ${LOG}

# see if the ipk is installed
INSTALLED=$(opkg list-installed "${IPK}")
#echo "Installed:${INSTALLED}"

# if already installed then exit
if [ -n "${INSTALLED}" ]; then
  echo "Installed, exiting" >> ${LOG}
  exit 0
fi

is_root_fs_readonly
echo "fs is readonly:${IS_FS_READONLY}" >> ${LOG}
  
if [ "${IS_FS_READONLY}" = true ]; then
  mount_root_fs_readwrite
fi

ensure_feed
  
echo "Installing... ${IPK}" >> ${LOG}
opkg install "${IPK}"

if [ "${IS_FS_READONLY}" = true ]; then
  mount_root_fs_readonly
fi
  
echo "Installed" >> ${LOG}
