#!/usr/bin/env bash
 
DBUS_SETTINGS="
    OpkgManager/CustomOverviewPages/NeShuntOverview:s:0:0:
	
		OpkgManager/CustomServices/NeShunt/ProductName:s:0:0:'Ne Shunt'
		OpkgManager/CustomServices/NeShunt/ServiceName:s:0:0:dbus-neshunt
"

#DBUS_SETTINGS_DEPRECIATED="
#		OpkgManager/CustomMenus/PageSettingsDisplay/PageSettingsNeShuntSubMenu:s:0:0:
#"

if [[ "$1" == "dev-install" ]]; then
  VE_ROOT_DIR=/data/dev/utils/opkg-manager/src
fi

source ${VE_ROOT_DIR:-}/data/opkg-manager/install-helper

if [[ "$1" == "install" || "$1" == "dev-install" ]]; then
	install_helper_post_install
elif [[ "$1" == "remove" ]]; then
	install_helper_pre_remove
fi

# install_helper_finished
 
