#!/usr/bin/env bash
 
RESTART_GUI_SERVICE=0
DBUS_SETTINGS="
    OpkgManager/CustomOverviewPages/OverviewNeShunt:s:0:0:
		OpkgManager/CustomMenus/PageSettings/PageSettingsNeShuntSubMenu:s:0:0:
"
 DBUS_SETTINGS_REMOVE="
		OpkgManager/CustomMenus/PageSettingsDisplay/PageSettingsNeShuntSubMenu:s:0:0:
"

if [[ "$1" == "dev-install" ]]; then
  VE_ROOT_DIR=/data/dev/utils/opkg-manager/src
fi

source ${VE_ROOT_DIR:-}/data/opkg-manager/install-helper

if [[ "$1" == "install" || "$1" == "dev-install" ]]; then
	install_helper_post_install

  #source "${VENUS_ROOT_DIR:-}/data/opkg-manager/serial-device-installer"
  #serial_device_installer_install && serial_device_installer_start_service
 
elif [[ "$1" == "remove" ]]; then
	install_helper_pre_remove
fi

# install_helper_finished
 
