#!/usr/bin/env bash
 
DBUS_SETTINGS="
    {'path':'/Settings/OpkgManager/CustomOverviewPages/NeShuntOverview', 'default':''}
	
		{'path':'/Settings/OpkgManager/CustomServices/NeShunt/ProductName', 'default': 'Ne Shunt'}
		{'path':'/Settings/OpkgManager/CustomServices/NeShunt/ServiceName', 'default':'dbus-neshunt'}
"

#DBUS_SETTINGS_DEPRECIATED="
#		{'path':'/Settings/OpkgManager/CustomMenus/PageSettingsDisplay/PageSettingsNeShuntSubMenu'}
#"

if [[ "$1" == "dev-install" ]]; then
  VE_ROOT_DIR=/data/dev/utils/opkg-manager/src
fi

source ${VE_ROOT_DIR:-}/data/opkg-manager/install-helper

if [[ "$1" == "install" || "$1" == "dev-install" ]]; then
	install_helper_post_install
elif [[ "$1" == "remove" ]]; then
	install_helper_pre_remove
fi

# install_helper_finished
 
