#!/bin/bash

# exit on error
set -e

# note shellcheck requires +xn arguments
# shellcheck source=./install-helper
source "${0%.*}".install-helper

##############################################################
# Install-helper. Prompts and detects usb serial devices
# Creates /data/dbus-ne-shunt/serial-starter.rule file
# Creates /data/dbus-ne-shunt/serial-starter.devname file
# Adds serial-starter.rule content to serial-serter.rules file
# When 'ensure-installed' script is run from rcS.local it uses 
# the files to automatically re-install after a firmware update.
##############################################################

SERVICE_NAME=$(basename "${0%.*}") #get file name without path
VE_SERVICE_MAPPING_NAME="neshunt"
TTY_FILE="/data/${SERVICE_NAME}/serial-starter.devname"
SERIAL_STARTER_RULE_FILE="/data/${SERVICE_NAME}/serial-starter.rule"
DBUS_MESSAGE_PATH="" #"com.victronenergy.packageManager /GuiEditStatus"
#TEST_USB_ID="1a86:55d3"

init_default_path_variables

install_usb_serial_device

add_ve_service_config_file_mapping
 
add_ensure_installed_script_to_rc_local

start_service

echo "${SERVICE_NAME} installed"

