#!/bin/bash

set -e

# note shellcheck requires +xn arguments
# shellcheck source=./install-helper
source "${0%.*}".install-helper

if [ -z "$D" ]; then

  SERVICE_NAME=$(basename "${0%.*}") #get file name without path
  VE_SERVICE_MAPPING_NAME="neshunt"
  TTY_FILE="/data/${SERVICE_NAME}/serial-starter.devname"
  SERIAL_STARTER_RULE_FILE="/data/${SERVICE_NAME}/serial-starter.rule"
  DBUS_MESSAGE_PATH="" #"com.victronenergy.packageManager /GuiEditStatus"
  #TEST_USB_ID="1a86:55d3"

  init_default_path_variables

  stop_and_remove_service

  remove_usb_serial_device

  remove_ve_service_config_file_mapping

  remove_ensure_installed_script_from_rc_local

  echo "${SERVICE_NAME}" removed

fi