baseurl: "/venus-os-addons"
layouts_dir: docs/assets/_layouts
remote_theme: pages-themes/primer

include:
  - docs
  - docs/assets/css

exclude:
  - addons
  - vendor

plugins:
  - jekyll-remote-theme
