#!/usr/bin/env bash
 
PATCH_SEPARATOR="===="
START_COMMENT="/*"
END_COMMENT="*/"
ACTION_INSERT_BEFORE="@insertbefore"
ACTION_INSERT_AFTER="@insertafter"
ACTION_REMOVE="@remove"
ACTION_FIND="@find"


# Read file into array FILE_LINES
# $1: the file to read the files from
read_file_lines() {
    local i line
    while IFS= read -r line || [ -n "$line" ]; do
        FILE_LINES[i]="$line"
        i=$((i+1))
    done < "$1"
}

# reads the patch file into the PATCH_LINES array.
# $1: the filename of the file to read
# PATCH_LENGTH is set to the number size of the array
read_patch_lines() {
    # $1: filename

    while IFS=: read -r line || [ -n "$line" ]; do
        PATCH_LINES[PATCH_LENGTH]="${line}"
        PATCH_LENGTH=$((PATCH_LENGTH+1))
    done < "$1"
    PATCH_LENGTH=$((PATCH_LENGTH+1))
}

# Writes the FILE_LINES array to file
# $1: the file name to write the FILE_LINES array too
write_file_lines() {
    printf "%s\n" "${FILE_LINES[@]}" >"$1"
}

# shellcheck disable=SC2329
# inserts a new line in the FILE_LINES array
# $1: the index in the FILE_LINES array to insert the new line at
# $2: the string to insert
insert_line() {
    insert_at_index=$1
    line_to_insert=$2
 
    FILE_LINES=("${FILE_LINES[@]:0:$insert_at_index}" "${line_to_insert}" "${FILE_LINES[@]:$insert_at_index}")
}

# inserts a slice of PATCH_LINES (from start index ($2) to end index ($3)) into the FILE_LINES at index ($1)
# $1 insert index
# $2 patch start index
# $3 patch end index
# requires read_file_lines & read_patch_lines methods have been called
insert_patch() {

    insert_at_index=$1
    patch_start_index=$2
    patch_len=$(($3-$2+1))

    FILE_LINES=("${FILE_LINES[@]:0:$insert_at_index}" "${PATCH_LINES[@]:patch_start_index:patch_len}" "${FILE_LINES[@]:$insert_at_index}")
}

# removes a range of lines from FILE_LINES using a start index and an end index
# $1: the start index
# $2: the end index
# requires read_file_lines & read_patch_lines methods have been called
# shellcheck disable=SC2329
remove_range() {
    remove_start_index=$1
    remove_end_index=$2
    remove_start_index=$((remove_start_index))
    remove_end_index=$((remove_end_index+1))

    FILE_LINES=("${FILE_LINES[@]:0:$remove_start_index}" "${FILE_LINES[@]:remove_end_index}")
}

# finds the end of a patch segment usualy definded by '===='
# $1: the start position of the patch segment
# requires read_patch_lines methods have been called
findPatchSegmentEnd() {

    local patchcurpos
    local p

    patchcurpos=$1
    for (( p=patchcurpos; p<PATCH_LENGTH; p++ ));
    do
        if [[ "${PATCH_LINES[$p]}" = "${PATCH_SEPARATOR}" ]]; then
            patch_end=$((p-1))
            break
        fi
    done
}

# resets the variables set by the find method
reset() {
    patch_end=-1
    patch_start=-1
    file_start=-1
    file_end=-1
}

# finds the text in the FILE_LINES array using the text segment from the PATCH_LINES array
# inputs:
# $1 = startfileindex
# $2 = startpatchindex
# outputs:
# file_start
# file_end
# patch_start
# patch_end
find() {

	local comment_start file_line f p
    
    startfileindex=$1
	startpatchindex=$2

	comment_start=-1
	reset
 
	for (( f=startfileindex; f<${#FILE_LINES[@]}; f++ ));
	do
		# trim white space
		file_line="$(echo "${FILE_LINES[$f]}" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"

		if [[ "${file_line}" == "${START_COMMENT}" ]] ; then
			comment_start=$f
		elif [[ $comment_start -gt -1 ]] && [[ "${file_line}" = "${END_COMMENT}" ]] ; then
			if [[ $file_end -gt -1 ]] && [[ $file_start -gt -1 ]] ; then
				file_end=$f
				break
			else 
				comment_start=-1
			fi
		fi
		
		for (( p="${startpatchindex}"; p<"${PATCH_LENGTH}"; p++ ));
		do
			if [[ "${FILE_LINES[$f]}" = "${PATCH_LINES[$p]}" ]] ; then
				if [[ $file_start -eq -1 ]] ; then
                    if [[ $comment_start -ne -1  ]] ; then
					    file_start=$comment_start
                    else
					    file_start=$f
                    fi
                    patch_start=$p
				fi
				f=$((f+1))
			elif [[ "${PATCH_LINES[$p]}" = "${PATCH_SEPARATOR}" ]] ; then
                f=$((f-1))
				file_end=$f
				patch_end=$p
				break
			else
				file_start=-1
                # shellcheck disable=SC2034
                patch_start=-1
				break
			fi
		done
		
		if [[ comment_start -eq -1 ]] && [[ file_start -gt -1 ]] && [[ file_end -gt file_start ]] ; then
            break
		fi
	done
}

# shellcheck disable=SC2329
# reads the commands in a <>.patch file and applys the result to a file
# $1: the file to apply the patch commands too
# $2: the file containing the patch commands to apply.  
apply_patch() { 
    local filename="$1"
    local patchfile="$2"

    read_file_lines "$file"
    read_patch_lines "$patchfile"
    
    local p insert_at_file_pos insert_patch_start 
 
    for (( p=0; p<"${PATCH_LENGTH}"; p++ ));
    do
        #echo "index: $p, value: ${PATCH_LINES[$p]}"
        if [[ "${PATCH_LINES[$p]}" == "${ACTION_FIND}" ]]; then
            
            p=$((p+1)) # advance past @find command
            # search FILE_LINES for matching lines contained in PATCH_LINES (upto end ''===='')
            find 0 "$p"
            p=$patch_end # set p to index at end of find text

        elif [[ "${PATCH_LINES[$p]}" == "${ACTION_INSERT_BEFORE}" ]] || [[ "${PATCH_LINES[$p]}" == "${ACTION_INSERT_AFTER}" ]] ; then
            
            [[ $file_start -eq -1 ]] && continue

            if [[ "${PATCH_LINES[$p]}" == "${ACTION_INSERT_BEFORE}" ]] ; then
                insert_at_file_pos=$((file_start))
            else
                insert_at_file_pos=$((file_end+1))
            fi
            
            insert_patch_start=$((p+1))

            # ensure patch has not already been applied
            # search FILE_LINES for matching lines contained in PATCH_LINES (upto end ''===='')
            find 0 $insert_patch_start
            if [[ $file_start -eq -1 ]] ; then
                findPatchSegmentEnd $insert_patch_start
                if [[ $patch_end -gt -1 ]] ; then
                    insert_patch $insert_at_file_pos $insert_patch_start $patch_end
                fi
            fi
        
            reset
        elif [[ "${PATCH_LINES[$p]}" == "${ACTION_REMOVE}" ]]; then
            p=$((p+1)) # advance past @find command
            find 0 "$p"
            [[ $file_start -eq -1 ]] && continue
            file_end=$((file_end+1))
            insert_line $file_end "${END_COMMENT}"
            insert_line $file_start "${START_COMMENT}"
        fi
    done

    write_file_lines "$filename"
}
 
# shellcheck disable=SC2329
# reverts the changes that were applied using the apply_patch method
# $1: the file to apply the patch commands too
# $2: the file containing the patch commands to revert.  
revert_patch() {
    FILE="$1"
    PATCH="$2"

    read_file_lines "$FILE"
    read_patch_lines "$PATCH"

    local p=0 insert_at_file_pos insert_patch_start 
 
    for (( p=0; p<"${PATCH_LENGTH}"; p++ ));
    do
        #echo "index: $p, value: ${PATCH_LINES[$p]}"
        if [[ "${PATCH_LINES[$p]}" == "${ACTION_REMOVE}" ]] ; then
            
            p=$((p+1))
            # shellcheck disable=SC2086
            find 0 $p
            if [[ $file_start -gt -1 ]] && [[ "${FILE_LINES[$file_start]}" == "/*" ]] ; then
                # shellcheck disable=SC2086
                remove_range $file_end $((file_end))
                # shellcheck disable=SC2086
                remove_range $file_start $((file_start))
            fi
        
            reset
        elif [[ "${PATCH_LINES[$p]}" == "${ACTION_INSERT_BEFORE}" ]] || [[ "${PATCH_LINES[$p]}" == "{${ACTION_INSERT_AFTER}}" ]] ; then

            # search FILE_LINES for matching lines contained in PATCH_LINES (upto end ''===='')
            p=$((p+1))
            # shellcheck disable=SC2086
            find 0 $p
            if [[ $file_start -gt -1 ]] ; then
                # shellcheck disable=SC2086
                remove_range $file_start $file_end
            fi
        
            reset
        fi
    done

    write_file_lines "$FILE"
}

BASH_ARGV1="apply"
BASH_ARGV2="/data/dev/services/dbus-ne-shunt/patch/test.working"
BASH_ARGV3="/data/dev/services/dbus-ne-shunt/patch/test.patch"

set -- "${BASH_ARGV1}" "${BASH_ARGV2}" "${BASH_ARGV3}"

cp "/data/dev/services/dbus-ne-shunt/patch/test.orig" "$2"

apply_patch "$2" "$3"
#revert_patch "$2" "$3"
exit 0

# Main
# shellcheck disable=SC2317
if [ "$1" = "apply" ]; then
    apply_patch "$2" "$3"
elif [ "$1" = "revert" ]; then
    revert_patch "$2" "$3"
else
    echo "Usage: $0 apply|revert <file_to_patch> <patch_file>"
    exit 1
fi