#!/bin/bash

set -o nounset

declare DEVICE_IP_ADDRESS="${1:-}"

#compiler_script=~/dev-local/gui-v2/tools/gui-v2-plugin-compiler.py
compiler_script=../../../../../../tooling/gui-v2-plugin-compiler.py

# Force Qt6 tools to avoid qtchooser wrappers (/usr/bin/lupdate, /usr/bin/rcc).
export PATH="/usr/lib/qt6/bin:/usr/lib/qt6/libexec:${PATH}"

if [[ ! -f "$compiler_script" ]]; then
  echo "/opt/victronenergy/gui-v2/gui-v2-plugin-compiler.py not found" >&2
  exit 1
fi

PLUGIN_NAME=Inetbox
MINIFY="--minify"
#PRE_COMPILE="--pre-compile"

[[ -z ${PRE_COMPILE:-} ]] && MINIFY=

# force delete so file size reporting is not using cache (when mounting/zfs etc)
rm -f ./${PLUGIN_NAME}.json

python3 "$compiler_script" \
    --name ${PLUGIN_NAME} \
    --min-required-version v1.2.13 \
    --settings InetboxPageSettings.qml ${MINIFY:-} ${PRE_COMPILE:-}
		#--pre-compile
		#--minify
#--devicelist 0xD01A Inetbox_devicelist_main.qml inetbox_page_title_simple

if [[ -n "${DEVICE_IP_ADDRESS}" ]]; then
  echo "--- copying plugin to device ${DEVICE_IP_ADDRESS}"
  scp "${PLUGIN_NAME}.json" "root@${DEVICE_IP_ADDRESS}:/tmp/${PLUGIN_NAME}.json"
  ssh root@"${DEVICE_IP_ADDRESS}" 'bash -s' << EOF
mkdir -p "/data/apps/available/${PLUGIN_NAME}/gui-v2" && \
  cp "/tmp/${PLUGIN_NAME}.json" "/data/apps/available/${PLUGIN_NAME}/gui-v2/${PLUGIN_NAME}.json"
mkdir -p /data/apps/enabled && \
  ln -sf "/data/apps/available/${PLUGIN_NAME}" /data/apps/enabled
svc -t /service/flashmq
rm -f /tmp/${PLUGIN_NAME}.json
EOF

fi

mkdir -p ../../../../src/data/apps/available/${PLUGIN_NAME}

cp ./output/${PLUGIN_NAME}.json \
		../../../../src/data/apps/available/${PLUGIN_NAME}/gui-v2/{PLUGIN_NAME}.json

echo "${MINIFY:-}" "${PRE_COMPILE:-}"
declare human="$(du -h "${PLUGIN_NAME}.json" | awk '{print $1}')"
declare bytes="$(wc -c < "${PLUGIN_NAME}.json")"
declare version=$(basename $(dirname $PWD))
echo "Plugin Size for: ${PLUGIN_NAME} $version: ${human} (${bytes})"