#!/usr/bin/env bash

# use echo $(<./backup-pi-proxmox.log) to get progress updates

images_path=/mnt/storage/images/

if [[ -n "${2}" ]]; then
  if [[ ! -f "${1}" ]]; then
    printf "Could not find file 's%'; exiting..." "${1}" >&2
    exit 1
  fi

  image_filename="${2}"

  if [[ -n "${1}" ]]; then

    # final check that we have an device path
    if lsblk -dpo name | grep -q "^${1}$"; then
      disk="${1}"
      sudo dd if="${disk}" iflag=fullblock bs=8M status=progress | gzip > "${image_filename}"
      echo "completed" >> "${0%.*}".log
      exit 0
    else
      echo "invalid device path:${2}; exiting..."
      exit 0
    fi
  fi

else

 read -p -r "Enter image file name to backup:" image_filename

fi

if [[ -z "${image_filename}" ]]; then
  echo "no image file name supplied; Exiting..."
  return
fi

# -e 11 (exclude CDROM drives")

echo
if lsblk -e 11 -o rm | grep -q " 1"; then
   echo "no removable disks found; exiting..."
   exit
fi

echo "=Disks==========================================================="
lsblk -e 11 -o name,size,type,tran,model,rm #| grep " 1$" | sed 's![^ ]*$!!')
echo "================================================================="

  # create an array with all the filer/dir inside ~/myDir
  PS3='Select the sdcard to backup (or CTRL+C):'

  # Choose the disk to restore to.
  # grep "1 disk$" is filtering only the removable disks. the 1 is the removable column.
  # -n=no headers,-d=no partitions, o= xxx,xxx=columns to return'
  # cut trims the end of the string so only the device path is displayed
  select disk in $(lsblk -p -ndo name,rm,type | grep "1 disk$" | cut -d ' ' -f 1)
  do
    # complain if no file was selected, and loop to ask again
    if [[ -z "${disk}" ]]; then
      echo "${REPLY} is not a valid number"
      continue
    fi

    # now we can use the selected file
    printf "'%s' selected" "${disk}"

    # it'll ask for another unless we leave the loop
    break
  done

echo
echo "backing up disk ${disk} to image ${images_path}${image_filename}"
while read -p -r "Do you want to proceed? (y/n) " confirm; do
  case "${confirm}" in
    y ) echo; break;;
    n ) echo exiting...;
            exit 0;;
    * ) echo invalid response;
            continue;;
  esac
done
# dummy sudo ls (ls could be any call) to elevate
# permissions before the nohup call
sudo ls 1>/dev/null 2>/dev/null

# here we use nohup so that the process works in the background and
# can logout of ssh terminals.
# we call this script again with the args we have set
# this is so that nohup names the process with the name of this script
# so its easy to find and kill if required.
# shellcheck disable=SC2016
echo 'use echo $(<./restore-pi.log) to get progress updates'

nohup "${0}" "${disk}" "${images_path}${image_filename}" > "${0%.*}".log &

sleep 1
tail -f "${0%.*}".log
