#!/usr/bin/env bash

# exit on error
set -e

ensure_feed() {

  local feed_config_file="/etc/opkg/thespinmaster.conf"
  if [[ -f $feed_config_file ]]; then
    echo "removing existing feed file"
    rm $feed_config_file
  fi
  echo "adding opkg feed"
  local feed_url="https://github.com/thespinmaster/venus-os/raw/refs/heads/main/feed"
  echo "src/gz thespinmaster $feed_url" > "$feed_config_file"
  
}

echo "configuring file system"
mount -o remount,ro /
/opt/victronenergy/swupdate-scripts/resize2fs.sh

# make /data the default folder for connecting via sftp
# find 'Subsystem       sftp    /usr/libexec/sftp-server'
# and add '-d /data' to the end
sed 's#Subsystem\s*sftp\s*/usr/libexec/sftp-server#Subsystem       sftp    /usr/libexec/sftp-server -d /data#' /etc/ssh/sshd_config 1>/dev/null

# make data the default folder when logging in via ssh 
echo "cd /data" >> ~/.profile

echo "ensuring spinmaster feed"
ensure_feed
opkg update

#TODO manualy add these packages to the /data/opkg-helpers/custom-packages.conf file
echo "replacing busybox"
opkg install packagegroup-replace-busybox

echo "installing python (full)"
opkg install python3

echo "installing additional packages"
opkg install libatomic1

echo "installing support for mounting network shares"
opkg install mount-shares

# () keeps . (source) to within bounds
(
  . /data/mount-shares/mount-helpers

  #source, username and password will be prompted for
  # store mnt under /data and not /mnt as mnt may be readonly 
  mount_helpers_mount_cifs --target="/data/mnt/dev"
)

if [[ ! -L "/data/dev" ]]; then
  ln -s "/data/mnt/dev" "/data/dev"
fi

echo "setting up environment (bash aliases, nanorc config)"
(
  . /data/opkg-helpers/opkg-common
  # priority 3 to execute after mount-shares
  declare rc_local_d_path=3
  opkg_common_ensure_rc_local_d rc_local_d_path
  
  # shellcheck disable=SC2217
  echo "#!/bin/bash

# setup enviroment (do not edit)
. /data/mount-shares/mount-helpers
mount_helpers_wait_on_mount_point \"/data/mnt/dev/\" &&
  /data/dev/projects/venus-os/tasks/setup-environment
" < "$rc_local_d_path/setup-environment"

    chmod +x "$rc_local_d_path/setup-environment"
    # execute script
    "$rc_local_d_path/setup-environment"
)

echo "dev environment setup completed successfully" 
