#!/usr/bin/env bash

# exit on error
set -e

ensure_feed() {

  local feed_config_file="/etc/opkg/opkg-manager-tmp.conf"
  if [[ -f $feed_config_file ]]; then
    echo "removing existing feed file"
    rm $feed_config_file
  fi
  echo "adding opkg feed"
  local feed_url="https://github.com/thespinmaster/venus-os/raw/refs/heads/main/feeds/opkg-manager"
  echo "src/gz thespinmaster $feed_url" > "$feed_config_file"
 
}

echo "configuring file system"
mount -o remount,ro /
/opt/victronenergy/swupdate-scripts/resize2fs.sh

# make /data the default folder for connecting via sftp
# find 'Subsystem       sftp    /usr/libexec/sftp-server'
# and add '-d /data' to the end
sed 's#Subsystem\s*sftp\s*/usr/libexec/sftp-server#Subsystem       sftp    /usr/libexec/sftp-server -d /data#' /etc/ssh/sshd_config 1>/dev/null

# make data the default folder when logging in via ssh 
echo "cd /data" >> ~/.profile

echo "ensuring spinmaster feed"
ensure_feed
opkg update

#echo "replacing busybox"
#opkg install packagegroup-replace-busybox

#echo "installing python (full)"
#opkg install python3

echo "installing git"
opkg install git

echo "installing additional packages"
opkg install libatomic1

echo "installing support for mounting network shares"
opkg install mount-shares

(
   # shellcheck source=/data/dev/utils/mount-shares/src/data/mount-shares/mount-common
  . /data/mount-shares/mount-common

  declare share_source share_username share_password

  # source, username and password are prompted here and passed through to mount.
  read -r -p "Enter server ip/host address and share path (example: //192.168.1.10/dev): " share_source
  read -r -p "Enter username for share: " share_username
  read -r -s -p "Enter password for share: " share_password
  echo

  # store mnt under /data and not /mnt as mnt may be readonly.
  # `unix` enables real symlink support on the CIFS dev share.
  # `unix` creates real symlinks unlike mfsymlinks.
  mount_common_mount --targetpath "/data/mnt/dev" -- \
    -t cifs \
    -o "username=${share_username},password=${share_password},exec,mfsymlinks" \
    "${share_source}"
)

if [[ ! -L "/data/dev" ]]; then
  ln -s "/data/mnt/dev" "/data/dev"
fi

echo "setting up environment (bash aliases, nanorc config)"
(
  # shellcheck source=/data/dev/utils/opkg-manager/src/data/opkg-manager/opkg-common
  . /data/opkg-manager/opkg-common
  # priority 3 to execute after mount-shares
  declare rc_local_d_path=3
  opkg_common_ensure_rc_local_d rc_local_d_path

  # shellcheck disable=SC2217
  echo "#!/bin/bash

# setup enviroment (do not edit)
  . /data/mount-shares/mount-common
mount_common_wait_on_mount_point \"/data/mnt/dev/\" &&
  cp /data/dev/projects/venus-os/tasks/setup-environment /data
  exec /data/setup-environment
" > "$rc_local_d_path/setup-environment"

    chmod +x "$rc_local_d_path/setup-environment"
    # execute script
    "$rc_local_d_path/setup-environment"
)

echo "dev environment setup completed successfully" 
