#!/usr/bin/env bash
 
####################################################################
# Creates all (default) the opkg packages in the folders
#   ../services, ../utils
# Ignored files/folders
#   .bak, .git, .tmp, /tests, -v[0-9], .old, .venv
# All files are staged (copied to ) ../.build and built from there.
# Symlinks are followed and copy the real file/directory
# Args:
#   Arg1:"all" (default): Builds all folders under under services & utils.
#   Arg[n]: Or a list of folders under services or utils to built
####################################################################

which opkg-build &>/dev/null || { echo "ERROR: opkg-build not installed"; exit 1; }

this_path="$(dirname "${BASH_SOURCE[0]}")"
 
if [[ -z "${1}" ]]; then
  build="all"
else
  build="${*}"
fi

declare -a build_items=()
declare -a folders=("../services" "../utils")
declare pwd_old=$PWD
declare -A update_feeds=()
 
cd "$this_path"

build_feed_index() {
  cd "${1}" || exit 1
  opkg-make-index -p Packages ./ 1>/dev/null
  echo "feed ${1} updated"
}

build_feed_indexes() {
  # Loop through all values in update_feeds and call build_feed_index
  for feed_path in "${update_feeds[@]}"; do
    build_feed_index "$feed_path"
  done
}

if [[ "$build" == "all" ]]; then
  #mapfile -t build_items < <(find "${folders[@]}" -mindepth 1 -maxdepth 1 -type d)
  echo "cur dir: $PWD"
  mapfile -t build_items < <(find "${folders[@]}" -mindepth 1 -maxdepth 1 -type d -exec realpath {} +)
elif [[ "$build" == "package" ]]; then
  build_feed_index "${2}"
else
  # shellcheck disable=SC2206
  build_items=(${build})
  #build_items=("opkg-manager" "test-service")
  declare -i found=0 i 
  declare f
  
  for i in "${!build_items[@]}"; do
    for f in "${folders[@]}"; do
      if [[ -d "$this_path/${f}/${build_items[$i]}" ]]; then
        build_items[i]="$this_path/$f/${build_items[$i]}"
        found=1
        break;
      fi
    done
    (( found==0)) && { echo "invalid package:${build_items[$i]}" >&2; exit 1; }
    found=0
  done
 
fi
 
# args: ${1} [in] build path (../.build)
#       ${2} in source path (../services/project-name)
#       ${3} [out] staging path (../.build/project-name)
stage_source_byref() {
  local build_path="${1}"
  local src_path="${2}"
  local dest_path
  local -n _staging_path="${3}"

  [[ "$src_path" =~ ^(\.\./)+(.*)$ ]]
  dest_path="$build_path/${BASH_REMATCH[2]}"

  options=(--exclude=*.bak --exclude=.git --exclude=*.tmp --exclude=tests/)
  options+=(--exclude=*-v[0-9] --exclude=*.old --exclude=.venv/)

  # Exclude directories containing .opkg-ignore
  while IFS= read -r rel_dir; do
    options+=(--exclude="$rel_dir/")
  done < <(
    find "$src_path" -type f -name ".opkg-ignore" -printf '%P\n' |
    xargs -r -n1 dirname
  )

  # `-a` enables archive mode (recursive copy and preserve file attributes/symlinks).
  # -L / --copy-links → follow symlinks and copy the real file/directory
  # `--mkpath` creates the destination path if it does not already exist.
  rsync -aL --mkpath "$src_path/" "$dest_path" "${options[@]}" || return 1
  _staging_path="$dest_path"
  return 0
}

set_feed_directory() {

  local name="${1}"
  local feed_name=

  if [[ "$name" == "opkg-manager" ]]; then
    feed_name="opkg-manager"
  else
    feed_name="main"
  fi

  update_feeds["${feed_name}"]="${this_path}/../feeds/${feed_name}"
  cd "${this_path}/../feeds/${feed_name}" || exit 1

}

build_package() {

  local path="${1}/src"
  local name; name="$(basename "${1}")"
 
  set_feed_directory "$name"

  echo "building ${name}"
 
  [[ -d "${path}" ]] || { echo "invalid path:${path}" >&2 ; return 1; }
 
  local build_path="../.build"
  local staging_path;
  stage_source_byref "$build_path" "$path" staging_path || return 1
  
  opkg-build -o root -g root "${staging_path}" ./

  rm -r "${build_path:?}/"*
 
}
 
for pkg in "${build_items[@]}"; do
  build_package "$pkg"
done

build_feed_indexes

cd "$pwd_old" || true
echo "Completed"
