#!/usr/bin/env bash
 
this_path="$(dirname "${BASH_SOURCE[0]}")"

declare comment=

if [[ -z "${1}" ]]; then
  build="all"
elif [[ "${1}" == "-c" ]]; then
  comment="${2}"
  shift 2
fi

declare -a build_items=()
declare -a folders=("../services" "../utils")
declare pwd_old=$PWD

cd "${this_path}/../feed" || exit 1

build_feed_package() {
  opkg-make-index ./ -p Packages
}
 
if [[ "$build" == "all" ]]; then
  mapfile -t build_items < <(find "${folders[@]}" -mindepth 1 -maxdepth 1 -type d)
elif [[ "$build" == "package" ]]; then
  build_feed_package
else
  build_items=("${@}")
  #build_items=("opkg-helpers" "test-service")
  declare -i found=0 i 
  declare f
 
  for i in "${!build_items[@]}"; do
    for f in "${folders[@]}"; do
      if [[ -d "${f}/${build_items[$i]}" ]]; then
        build_items[i]="$f/${build_items[$i]}"
        found=1
        break;
      fi
    done
    (( found==0)) && { echo "invalid package:${build_items[$i]}" >&2; return 1; }
    found=0
  done
 
fi
 
build_package() {

  path="${1}/src"
  name="$(basename "${1}")"
  echo "building ${name}"

  [[ -d "${path}" ]] || { echo "invalid path:${path}" >&2 ; return 1; }

  opkg-build -o root -g root "${path}" ./

}
 
for pkg in "${build_items[@]}"; do
  build_package "$pkg"
done

build_feed_package

if [[ -n "$comment" ]]; then
  git add .
  git commit -am "${comment}"
  git push
fi

cd "$pwd_old" || true