#!/bin/sh
set -e
if [ -z "$D" ]; then
  
  SERVICE_NAME=$(basename "${0%.*}") #get file name without path

  # copy service, svscan will detect the new files & avoid a reboot
  cp -R "/opt/victronenergy/service/${SERVICE_NAME}/" /service/
  
  ################################################
  # Adding ensure-installed to rc.local
  ################################################
  RC_LOCAL_FILE="/data/rc.local"
  RC_LOCAL_ACTION="/data/${SERVICE_NAME}/ensure-installed"
  if ! grep -q "^${RC_LOCAL_ACTION}$" "${RC_LOCAL_FILE}"; then
    echo "adding ${RC_LOCAL_ACTION} to ${RC_LOCAL_FILE}"
    echo "${RC_LOCAL_ACTION}" >> "${RC_LOCAL_FILE}"
    chmod +x "${RC_LOCAL_FILE}"
  fi
  ################################################

  echo "${SERVICE_NAME} installed"
fi
