#!/bin/sh
set -e
if [ -z "$D" ]; then
  
  SERVICE_NAME=$(basename "${0%.*}") #get file name without path

  # create the conf file
  # used in the network-gps service
  CONF_FILE="/data/network-gps/network-gps.conf"
  if [ ! -f "$CONF_FILE" ]; then
    cat << EOF > "$CONF_FILE"

EOF
  fi

  # copy service.
  # svscan will detect the new files, avoiding a reboot
  cp -R /opt/victronenergy/service/network-gps/ /service/

  ################################################
  # Adding ensure-installed to rc.local
  ################################################
  RC_LOCAL_FILE="/data/rc.local"
  RC_LOCAL_ACTION="/data/${SERVICE_NAME}/ensure-installed"
  if ! grep -q "^${RC_LOCAL_ACTION}$" "${RC_LOCAL_FILE}"; then
    echo "adding ${RC_LOCAL_ACTION} to ${RC_LOCAL_FILE}"
    echo "${RC_LOCAL_ACTION}" >> "${RC_LOCAL_FILE}"
    chmod +x "${RC_LOCAL_FILE}"
  fi
  ################################################

  echo "${SERVICE_NAME} installed"
fi
