#!/usr/bin/env bash

# this_path="$(dirname "${BASH_SOURCE[0]}")"

QML_TARGET_FOLDER="${VENUS_ROOT_DIR:-}/opt/victronenergy/gui/qml"
QML_SOURCE_FOLDER="${VENUS_ROOT_DIR:-}/opt/victronenergy/gui/qml/Theming"

__appendDataDir() {
	local VENUS_DATA_DIR="/data/dev/utils/opkg-manager/src"; [ -d $VENUS_DATA_DIR ] || VENUS_DATA_DIR=
  local file="${1}"
	local -n _out_dir=${2}
	_out_dir="${VENUS_DATA_DIR:-}/data/opkg-manager/${file}"
}
# List of special pages (without .qml)
__load_source_file() {
		# may require symlink to /data/dev 
  local source_file=
	__appendDataDir "${1}" source_file
	[[ -f ${source_file} ]] || { echo "ERROR: source file does not exist:${source_file}" >&2; exit 1; }

	# shellcheck disable=SC1090
	. "${source_file}"
	
}

__apply_patch() {
	__load_source_file "file-patcher"
	
	local patchFile=
	__appendDataDir "themer.patch" patchFile

	opkg_file_patcher_apply_patch "$patchFile"
}

__revert_patch() {
	__load_source_file "file-patcher"
	
	local patchFile=
	__appendDataDir "themer.patch" patchFile

	opkg_file_patcher_apply_patch "$patchFile"
}

__add_remove_dbus_settings() {
	
	local -i remove=${1:-0} # 0 adds; 1 removes
	__load_source_file "dbus-common"

	local settings='
		Theme:s:0:0:"dark"
		TextColor:s:0:0:"#ffffff"
		BackgroundColor:s:0:0:"#1f1f1f"
		BackgroundColor2:s:0:0:"#313131"
		IconSuffixNormal:s:0:0:"active"
		IconSuffixSelected:s:0:0:"active"
		BorderColor:s:0:0:"#3c3c3c"
		Enabled:i:0:1:1
	'
 
	dbus_common_add_remove_debus_settings $remove "Themer" "$settings"
 
}
 
install_helper_post_install() {
	
	(
		__load_source_file "opkg-common"
		opkg_common_register_package "themer"
	)

	(
		__load_source_file "file-patcher"
		opkg_file_patcher_apply_patch "themer.patch"
	)

	(
		themer_common_add_remove_dbus_settings 0 # 0 to add
	)
 
}

install_helper_pre_remove() {

	(
		__load_source_file "opkg-common"
		opkg_common_unregister_package "themer"
	)

	(
		__load_source_file "file-patcher"
		local this_path="$(dirname "${BASH_SOURCE[0]}")"
		opkg_file_patcher_revert_patch "$this_path/themer.patch"
	)

	(
		themer_common_add_remove_dbus_settings 1 # 1 to remove
	)
 
}

#themer_common_patch_files
#themer_common_remove_patch_from_files
#themer_common_add_remove_dbus_settings 1
