#!/bin/bash

source /data/opkg-helpers/opkg-common.sh

PACKAGE_NAME=$(basename "${0%.*}") #get file name without path

add_package_name_to_custom_packages_file "${PACKAGE_NAME}"

echo "${PACKAGE_NAME} installed"
