#!/bin/bash

#source /data/opkg-helpers/install-helper.sh
#source /data/opkg-helpers/opkg-common.sh

PACKAGE_NAME=$(basename "${0%.*}") #get file name without path

/data/opkg-helpers/opkg-common.sh "postrm" "${PACKAGE_NAME}"

echo "${PACKAGE_NAME} removed"