#!/bin/bash

#source /data/opkg-helpers/install-helper.sh
source /data/opkg-helpers/opkg-common.sh

PACKAGE_NAME=$(basename "${0%.*}") #get file name without path

remove_package_name_from_custom_packages_file "${PACKAGE_NAME}"

echo "${PACKAGE_NAME} removed"