#!/bin/bash

declare package_name=$(basename "${0%.*}") #get file name without path

source "${VENUS_ROOT_DIR:-}/data/opkg-manager/opkg-common"
opkg_common_unregister_package "${package_name}"

echo "${package_name} removed"