#!/bin/bash

#source /data/opkg-helpers/install-helper.sh

PACKAGE_NAME=$(basename "${0%.*}") #get file name without path

/data/opkg-helpers/opkg-common.sh "postinst" "${PACKAGE_NAME}"

echo "${PACKAGE_NAME} installed"
