#!/bin/bash

declare package_name=$(basename "${0%.*}") #get file name without path

source "${VENUS_ROOT_DIR:-}/data/opkg-helpers/opkg-common"
opkg_common_register_package "${package_name}"

echo "${package_name} installed"
