#!/usr/bin/env bash
 
: ' 
  WHEN UDEVADM_PROPS empty THEN
    detect usb using usb monitor
        fills TTY (done __fill_prop_values_from_tty_when_not_headless)
        from TTY fill UDEVADM_PROPS (done __fill_props_from_tty)
  OTHERWISE
      find USB_DEVPATH from UDEVADM_PROPS
      find TTY from USB_DEVPATH
'
set -o nounset

__this_path="$(dirname "${BASH_SOURCE[0]}")"
. "$__this_path/libs/log-lib"

INTERACTIVE=1
 
# requires: SERVICE_NAME
# optional: SERVICE_MAPPING_NAME
# args_byref service_mapping_name
__get_service_mapping_name_byref() {
  local -n _service_mapping_name="${1}"
  _service_mapping_name="${SERVICE_MAPPING_NAME:-}"
  [[ -z "${_service_mapping_name}" ]] && { _service_mapping_name="ve_${SERVICE_NAME}"; }
}

# requires: UDEVADM_PROPS
# args_byref props
# args_byref count_of_filled
__count_of_filled_props_byref() {
  local -n _out_props=${1}
  local -n _count_of_filled=${2}
  _count_of_filled=0
  for key in "${!_out_props[@]}"; do
    [[ -n "${_out_props[$key]}" ]] && (( _count_of_filled+=1 ))
  done
  return 0
}


# requires: UDEVADM_PROPS
# args_byref props
# optional args_byref count
__are_all_prop_values_filled() {
  local -n _out_props=${1}
  local -n count=${2:--1}
  ((count==-1)) && 
    __count_of_filled_props_byref count

  (( count = "${#_out_props[@]}" )) && return 0
  return 1
}

 
# requires vars: UDEVADM_PROPS
# required args: props_byref
__read_props_byref() {
 
  local -n _out_props="$1";
  local -a __props
  local -A new_props
  local key value
 
  # Split the string into array by NUL character
  IFS='|' read -r -a __props <<< "$UDEVADM_PROPS"
  for key_value in "${__props[@]}"; do
    k="${key_value%%=*}"; 
    value=
    [[ "$key_value" == *"="* ]] && value="${key_value#*=}"
    [[ "$k" =~ ^[a-zA-Z0-9_]+$ ]] || { echo "UDEVADM_PROPS are invalid" >&2; return 1; }
 
    new_props["$k"]="$value"
  done
 
  # array was loaded without any erros so unset 
  # the origional values and add the new ones
  for k in "${!_out_props[@]}"; do unset "_props[$k]"; done
  for k in "${!new_props[@]}"; do 
     _out_props["$k"]="${new_props[$k]}"; 
  done

  return 0
}
 
# requires vars: UDEVADM_PROPS
__write_props() {
  # shellcheck disable=SC2178
  local -n _props=$1
  local key
 
  UDEVADM_PROPS=""
  for k in "${!_props[@]}"; do
    UDEVADM_PROPS+="$k=${_props[$k]}"$'|'
  done
  [[ "${UDEVADM_PROPS:(-1)}" == $'|' ]] &&
    UDEVADM_PROPS="${UDEVADM_PROPS::-1}"

}

# requires vars: UDEVADM_PROPS
# args = {1} tty
# args = {2} in,out props
__fill_props_from_tty() {
  
  local tty="${1}"
  [[ -z "${tty}" ]] && { echo "ERROR: TTY not set;" >&2; return 1; }

  # shellcheck disable=SC2178
  local -n __props=${2}

  local props_to_grep=""
  for k in "${!__props[@]}"; do props_to_grep+="$k=|"; done
  props_to_grep=${props_to_grep::-1}
  
  usb_info_lines=$(udevadm info --name="/dev/${tty}" --query=property | grep -E "${props_to_grep}")
  
  local key value
  local -i filled_count=0
  while IFS= read -r line; do
    key="${line%%=*}"
    value="${line#*=}"
    [[ -z "${key}" ]] && continue
    __props["${key}"]="${value}"
    ((filled_count+=1))
  done <<<"${usb_info_lines}"
  
  #for k in "${!props[@]}"; do echo "$k=${props[$k]}"; done

  __write_props __props
 
  (( filled_count==0 )) && {
    echo "ERROR: no UDEVADM_PROPS found" >&2; return 1; }

  # This is a warning so we return 0 but log to stderr
  ((filled_count!=${#__props[@]}  ))  && {
    echo "WARNING: not all UDEVADM_PROPS found" >&2; return 0; } 

  return 0
}

# requires vars: UDEVADM_PROPS
# optional vars: USE_UDEVADM_MONITOR, USB_TIMEOUT
__get_tty_port() {
  log_trace
  
  local -n _tty="${1}"

  ((INTERACTIVE)) || { echo "cannot request usb device, running headless" >&2; return 1; }
   
  log "Plug in (or re-plugin) the usb device now...timeout in ${USB_TIMEOUT} seconds"

  if [[ ${USE_UDEVADM_MONITOR} ]]; then
    local get_usb_port
    get_usb_port="$(dirname "${BASH_SOURCE[0]}")/get-usb-port"
    [[ -f "$get_usb_port" ]] || {
      echo "get-usb-port file not found:$get_usb_port" >&2
      return 1
    }
    timeout=${USB_TIMEOUT:-30}
    _tty=$("${get_usb_port}" --silent --timeout "${timeout}")
  else
    __detect_inserted_serial_usb_device
  fi

  [[ -z "${_tty}" ]] && {
    log_error "No new USB device found."
    return 1
  }

  log "Found new USB device: ${_tty}"

  return 0
}

# args: in byref props
# args: {2} out byref props_to_grep
__prepare_props_for_grep_byref() {
  # shellcheck disable=SC2178
  local -n __props="${1}"
  local -n __props_to_grep="${2}"
  for k in "${!__props[@]}"; do __props_to_grep+="$k=|"; done
  __props_to_grep=${__props_to_grep::-1}
}

#args: {1} dev_path, {2} byref out tty
__get_tty_paths() {
  local -n _out=$1
  _out=(/sys/class/tty/ttyUSB* /sys/class/tty/ttyACM*)
}
 
# args: in byref props
# args: {2} out byref tty
__get_tty_from_props_byref() {
  
  local -n _props="${1}"
  local -n out_tty="${2}"
  local usb_dev_path
  local -i count_of_filled_props=0 count_of_matched_props=0
  local -i usb_def_path_index=0 found_index=-1
  local props_to_compare
  local -a tty_paths=(); __get_tty_paths tty_paths
  local props_to_grep="DEVPATH|"
  
  out_tty=

  __prepare_props_for_grep_byref _props props_to_grep
  __count_of_filled_props_byref _props count_of_filled_props
 
  for dev in "${tty_paths[@]}"; do
    [ -e "$dev" ] || continue

    props_to_compare=$(udevadm info -q property -p "$dev" | grep -E "${props_to_grep}")
  
    local key value
 
    while IFS= read -r line; do
      [[ $line =~ ^DEVPATH=* ]] && {
        usb_dev_path=${line#*=}; continue; }

      key="${line%%=*}"; value="${line#*=}"
      [[ -z "${key}" ]] && continue
      [[ "${_props[${key}]}" == "${value}" ]] && ((count_of_matched_props+=1))
    done <<<"${props_to_compare}"
 
    ((count_of_filled_props==count_of_matched_props)) && {
      ((found_index+=1))

      ((found_index==usb_def_path_index)) && break;
    }
    usb_dev_path=

  done
  
  if  [[ $usb_dev_path ]]; then
    # shellcheck disable=SC2034
    out_tty=$(basename "$usb_dev_path")
    return 0
  fi

  echo "ERROR: tty device does not exist" >&2
  return 1
}

################################################################
################################################################

# requires vars: USB_TIMEOUT
# required args: arg1_byref
__detect_inserted_serial_usb_device() {

  log_trace

  local counter=0
  local timeout_counter=0
  local progress_header_msg="Please connect the serial device (or remove and reconnect it) to the USB port."
  local before_usb_devices

  before_usb_devices=$(lsusb)

  echo "${progress_header_msg}"
  echo "Waiting for USB device to be connected..."

  while true; do
    sleep 1
    local after_usb_devices; after_usb_devices=$(lsusb)
    local before_count after_count

    before_count=$(echo "$before_usb_devices" | wc -l)
    after_count=$(echo "$after_usb_devices" | wc -l)
    if [[ $after_count -eq $((before_count + 1)) ]]; then
      local new_device
      new_device=$(comm -13 <(echo "$before_usb_devices") <(echo "$after_usb_devices"))
      echo "$new_device"
      return
    else
      before_usb_devices="$after_usb_devices"
    fi

    counter=$((counter + 1))
    [[ $counter -gt 3 ]] && counter=1
    timeout_counter=$((timeout_counter + 1))
    if [[ $timeout_counter -gt ${USB_TIMEOUT} ]]; then
      echo "Timeout, exiting..."
      return
    fi
    echo -n "No new USB device detected, retrying$(printf '.%.0s' $(seq 1 $counter))  " true
  done
}

# requires vars: SERVICE_NAME, SERVICE_MAPPING_NAME, UDEVADM_PROPS
# required arg1_byref
__create_serial_starter_rule_byref() {

  log_trace
  
  local -n _props=${1}

  [[ -z "${SERVICE_NAME}" ]] && { log_error "ERROR: SERVICE_NAME not set"; return 1; }
 
  local service_mapping_name; __get_service_mapping_name_byref service_mapping_name
  local -n out_serial_starter_rule; out_serial_starter_rule=${2}
  local kv k rules=""
 
  for kv in "${!_props[@]}"; do
    [[ -z "${_props[$kv]}" ]] && continue
    rules+="ENV{${kv}}==\"${_props[$kv]}\","
  done
  [[ "${rules:(-1)}" == $',' ]] && rules="${rules::-1}"

  log_trace "udevadm matches ${rules}"
  if [[ -z "${rules}" ]]; then
    log_error "ERROR: No UDEVADM_PROPS values set."
    return 1
  fi
 
  out_serial_starter_rule="ACTION==\"add\", $rules, ENV{VE_SERVICE}=\"${service_mapping_name}\""
 
  log_trace "new SERIAL_STARTER_RULE=${out_serial_starter_rule}"

  return 0
}

# requires vars: SERIAL_STARTER_RULES_FILE, SERIAL_STARTER_RULES_TEXT_MATCH, SERVICE_NAME
# required args: {1}= serial_starter_rule
__add_rule_to_serial_starter_rules_file() {

  log_trace

  local serial_starter_rule; serial_starter_rule="${1}"
  [[ -z "${serial_starter_rule}" ]] && { log_error "ERROR: serial starter rule not set"; return 1; }
  [[ -f "${SERIAL_STARTER_RULES_FILE}" ]] || {
    log_error "ERROR: file not found, SERIAL_STARTER_RULES_FILE:${SERIAL_STARTER_RULES_FILE}"
    return 1
  }
  
  if grep -qF "${serial_starter_rule}" "${SERIAL_STARTER_RULES_FILE}"; then
    log "Rule already exists in the file."
    return 0
 
  fi

  local rule_with_comment; rule_with_comment="# ${SERVICE_NAME}"$'\n'"${serial_starter_rule}"$'\n'
  
  [[ -z "${SERIAL_STARTER_RULES_TEXT_MATCH}" ]] && {
    # add run to the end of the file
    echo "${rule_with_comment}" >> "${SERIAL_STARTER_RULES_FILE}"
    return 0
  }

  log "Adding new rule to serial starter rules file..."
  log "after line ending:${SERIAL_STARTER_RULES_TEXT_MATCH}"
  
  local -i _found=
  local new_rules="" nl=$'\n'
 
  while IFS= read -r line || { [[ -n "$line" ]]; }; do
    new_rules+="${line}${nl}"
    ((_found)) && continue
    if [[ "$line" = *"${SERIAL_STARTER_RULES_TEXT_MATCH}" ]]; then
      new_rules+="${rule_with_comment}${nl}"
      _found=1
    fi
  done <"${SERIAL_STARTER_RULES_FILE}"

  ((!_found)) && {
    log_error "ERROR: SERIAL_STARTER_RULES_TEXT_MATCH: insert location not found"
    return 1
  }

  echo "${new_rules}" >"${SERIAL_STARTER_RULES_FILE}" || {
    log_error "ERROR adding rule to ${SERIAL_STARTER_RULES_FILE}" 
    return 1
  }
  log "Rule added successfully."
  return 0
}

# required vars: SERIAL_STARTER_RULES_FILE, SERVICE_NAME
# required args: args1 serial_starter_rule
__remove_rule_from_serial_starter_rules_file() {

  log_trace
  
  local serial_starter_rule="${1}"

  [[ -n "${serial_starter_rule}" ]] || { 
    log_error "serial starter rule not set, nothing to do"; return 0; }
  
  [[ -f "${SERIAL_STARTER_RULES_FILE}" ]] || {
    log_error "ERROR: file not found, SERIAL_STARTER_RULES_FILE:$SERIAL_STARTER_RULES_FILE"; return 1; }

  local rules; rules="$(<"${SERIAL_STARTER_RULES_FILE}")"
  local comment new_rules; new_rules="$rules"

  comment="# $SERVICE_NAME"$'\n'
  new_rules="${new_rules/${serial_starter_rule}/}"
 
  if [[ "${new_rules}" != "${rules}" ]]; then
    echo -e "${new_rules}" > "${SERIAL_STARTER_RULES_FILE}"
    new_rules="${new_rules/${comment}/}"
    
    log "successfully removed rule from ${SERIAL_STARTER_RULES_FILE}"
  fi

  return 0
}

# required vars: SERIAL_STARTER_CONFIG_FILE, SERVICE_MAPPING_NAME, SERVICE_NAME
__add_ve_service_config_file_mapping() {

  log_trace

  [[ -f "$SERIAL_STARTER_CONFIG_FILE" ]] || {
    log_error "ERROR: file not found SERIAL_STARTER_CONFIG_FILE:$SERIAL_STARTER_CONFIG_FILE"
    return 1
  }

  local service_mapping_name; __get_service_mapping_name_byref service_mapping_name
 
  #Try to allign with existing services
  #18=24 - 8 = 16; (24 is mapping offset - 8 for 'service ' len)
  local -i spaces_len; spaces_len=$((16 - "${#service_mapping_name}"))
  ((spaces_len < 1)) && spaces_len=1

  local spaces; spaces=$(head -c $spaces_len </dev/zero | tr '\0' ' ')
  entry="service ${service_mapping_name}${spaces}${SERVICE_NAME}"
  find_pattern="^[[:space:]]*service[[:space:]]+${service_mapping_name}[[:space:]]+${SERVICE_NAME}[[:space:]]*$"
 
  if ! grep -Eq "${find_pattern}" "${SERIAL_STARTER_CONFIG_FILE}"; then
    log "adding ve service mapping config to ${SERIAL_STARTER_CONFIG_FILE}"
    sed -i '1s/^/'"${entry}"'\n/' "${SERIAL_STARTER_CONFIG_FILE}"
  else
    log "ve service mapping already exists"
  fi

}

# requires vars: SERIAL_STARTER_CONFIG_FILE, SERVICE_NAME
# optional vars: SERVICE_MAPPING_NAME
__remove_ve_service_config_file_mapping() {

  log_trace

  [[ -f "${SERIAL_STARTER_CONFIG_FILE}" ]] || {
    log_info "serial starter conf file not found"
    return 2
  }

  local service_mapping_name; __get_service_mapping_name_byref service_mapping_name
  
  pattern="^[[:space:]]*service[[:space:]]\+${SERVICE_MAPPING_NAME}[[:space:]]\+${SERVICE_NAME}[[:space:]]*$"

  tmp=$(mktemp)
  sed "/$pattern/d" "$SERIAL_STARTER_CONFIG_FILE" >"$tmp"

  local log_info="\'service ${service_mapping_name} ${SERVICE_NAME}\' in $SERIAL_STARTER_CONFIG_FILE"
  if cmp -s "$SERIAL_STARTER_CONFIG_FILE" "$tmp"; then
    log "ve service mapping not found:${log_info}"
    rm "$tmp"
  else
    mv "$tmp" "$SERIAL_STARTER_CONFIG_FILE"
    log "Sucessfully removed ve service mapping:${log_info}"
  fi
}

# validates: SERVICE_NAME, UDEVADM_PROPS, SERIAL_STARTER_RULES_FILE, SERIAL_STARTER_CONFIG_FILE
__validate_all() {

  [[ -z "${SERVICE_NAME:-}" ]] && {
    log_error "ERROR: SERVICE_NAME not set"
    return 1
  }
  [[ -z "${UDEVADM_PROPS:-}" ]] && {
    log_error "ERROR: UDEVADM_PROPS not set"
    return 1
  }
 
  [[ -f "${SERIAL_STARTER_RULES_FILE:-}" ]] || {
    log_error "ERROR: file not found, SERIAL_STARTER_RULES_FILE:$SERIAL_STARTER_RULES_FILE"
    return 1
  }
  [[ -r "${SERIAL_STARTER_RULES_FILE:-}" ]] || {
    log_error "ERROR: SERIAL_STARTER_RULES_FILE does not have read access:$SERIAL_STARTER_RULES_FILE"
    return 1
  }
  [[ -w "${SERIAL_STARTER_RULES_FILE:-}" ]] || {
    log_error "ERROR: SERIAL_STARTER_RULES_FILE does not have write access:$SERIAL_STARTER_RULES_FILE"
    return 1
  }

  [[ -f "${SERIAL_STARTER_CONFIG_FILE:-}" ]] || {
    log_error "ERROR: file not found, SERIAL_STARTER_CONFIG_FILE:$SERIAL_STARTER_CONFIG_FILE"
    return 1
  }
  [[ -r "${SERIAL_STARTER_CONFIG_FILE:-}" ]] || {
    log_error "ERROR: SERIAL_STARTER_CONFIG_FILE does not have read access:$SERIAL_STARTER_CONFIG_FILE"
    return 1
  }
  [[ -w "${SERIAL_STARTER_CONFIG_FILE:-}" ]] || {
    log_error "ERROR: SERIAL_STARTER_CONFIG_FILE does not have write access:$SERIAL_STARTER_CONFIG_FILE"
    return 1
  }
}
 
###################################################
# public methods
###################################################

# required vars: SERVICE_NAME, UDEVADM_PROPS, 
#                SERIAL_STARTER_RULES_FILE, SERIAL_STARTER_CONFIG_FILE
#                SERIAL_STARTER_START_SERVICE_PATH, SERVICE_PATH
# optional vars: TTY, SERVICE_MAPPING_NAME, USE_UDEVADM_MONITOR,
#                SERIAL_STARTER_RULES_TEXT_MATCH, USB_TIMEOUT
serial_device_installer_install() {
  
  __validate_all || return 1
  
  local tty; 

  local -A props; __read_props_byref props || return 1
  local -i count; __count_of_filled_props_byref props count || return 1
  if ((count==0)); then
    __get_tty_port tty || return 1
    __fill_props_from_tty "$tty" props || return 1
  else
     __get_tty_from_props_byref props tty
  fi

  log "Installing USB serial device..."
 
  local serial_starter_rule
  __create_serial_starter_rule_byref props serial_starter_rule || return 1

  __add_rule_to_serial_starter_rules_file "${serial_starter_rule}" || return 1
 
  __add_ve_service_config_file_mapping || return $?
  
  TTY=$tty
  return 0
}
 
################################################
# Removes the rule added to the serial-starter.rules file
# Removes the service mapping from the serial-starter.conf file
# Sets TTY var to empty
# required vars: SERVICE_NAME, UDEVADM_PROPS
################################################
serial_device_installer_remove() {

  log_trace

  local -A props; __read_props_byref props || return 1
  local serial_starter_rule; __create_serial_starter_rule_byref props serial_starter_rule || return 1

  __remove_rule_from_serial_starter_rules_file "${serial_starter_rule}" || return 1
 
  __remove_ve_service_config_file_mapping || return 1

 
}

################################################
# Add a file (ttyACME) to /dev/serial-starter/
# this file is picked up by the serial-starter
# and starts the service.
# Requires variables:
# TTY, SERVICE_NAME, SERIAL_STARTER_START_SERVICE_PATH
################################################
serial_device_installer_start_service() {

  log_trace
  
  local tty="${1:-}"
   
  [[ -d "${SERIAL_STARTER_START_SERVICE_PATH}" ]] || {
    log_error "ERROR: SERIAL_STARTER_START_SERVICE_PATH not set or does not exist"
    return 1
  }
  [[ -z "${SERVICE_NAME}" ]] && {
    log_error "ERROR: SERVICE_NAME not set"
    return 1
  }
 
  if [[ -z "$tty" ]]; then 
    local -A props; __read_props_byref props || return 1
    __get_tty_from_props_byref props tty || return 1
  else
    [[ -e "/dev/${TTY}" ]] || { log_error "ERROR: TTY device does not exist"; return 1; }
  fi
 
  log "starting service ${SERIAL_STARTER_START_SERVICE_PATH}/${SERVICE_NAME}.${tty}"
  touch "${SERIAL_STARTER_START_SERVICE_PATH}/${tty}"
  return 0
}

#########################################
# Stops the service using the serial port
# removes the directory /SERVICE_PATH/SERVICE_NAME.TTY
# Requires variables:
# TTY, SERVICE_PATH, SERVICE_NAME
#########################################
serial_device_installer_stop_and_remove_service() {

  ################################################
  # Stop the service
  # Reads the tty name from the serial-starter.devname
  # file and combines it with the SERVICE_NAME to make
  # the full service name i.e. dbus-ne-shunt.ttyACM0
  ################################################
  log_trace
  
  local tty="${1:-}"
  
  [[ -z "${SERVICE_NAME}" ]] && { log_error "ERROR: SERVICE_NAME not set"; return 1; }
  [[ -d "${SERVICE_PATH}" ]] || { log_error "ERROR: SERVICE_PATH not found"; return 1; }
 
  if [[ -z "$tty" ]]; then 
    # shellcheck disable=SC2034
    local -A props; __read_props_byref props || return 1
    __get_tty_from_props_byref props tty || return 1
  else
    [[ -e "/dev/${TTY}" ]] || { log_error "ERROR: TTY device does not exist"; return 1; }
  fi

  local full_service_path="${SERVICE_PATH}/${SERVICE_NAME}.${TTY}"
  log_trace "full_service_path=${full_service_path}"
  if [ -d "${full_service_path}" ]; then
    log "stopping service ${full_service_path}"
    svc -d "${full_service_path}" 2>/dev/null
    sleep 3 # secs
    rm -R "${full_service_path}" 2>/dev/null
  else
    log_error "ERROR: could not find service: ${full_service_path}"
    return 1
  fi

}

################################################################
################################################################
