#!/usr/bin/env bash

set -o nounset

declare _this_path; _this_path=$(dirname "${BASH_SOURCE[0]}")
declare DEFAULT_USB_PROPS="ID_MODEL,ID_VENDOR,ID_SERIAL,ID_PATH"
declare dbus_available_devices_prefix="/Settings/OpkgManager/Devices"

source "$_this_path/../dbus-common"
source "$_this_path/../service-common"
source "$_this_path/../serial-device-installer"

device_remove_all() {
	local settings_list= line= sid=

	dbus_common_list_keys /Settings/Devices settings_list

	while IFS= read -r line; do
		sid="${line%/Sid}"
		sid="${sid##*/}"
		sid="${sid#sid_}"
		device_remove $sid
	done < <(printf '%s\n' "$settings_list" | grep '/Sid$')
}

device_remove() {

	DEVICE_SID="${1}"
	[[ -z "$DEVICE_SID" ]] && { echo "Invalid argument: sid empty" >&2; return 1; }

	dbus_common_delete_tree "/Settings/Devices/sid_${DEVICE_SID}"

	serial_device_installer_remove_service

	return 0
}

device_scan_usb() {
	local -i discovered_count=0
	local tty
	local usbProps=

	for tty in $(serial_device_installer_get_available_devices); do

		serial_device_installer_fill_usb_props $tty $DEFAULT_USB_PROPS usbProps || { continue; }
		serial_device_installer_set_device_sid $usbProps
		usbProps=$(printf '%s\n' "$usbProps" | sed 's/,\?ID_PATH=[^,]*//')

		printf 'DEVICE:DISCOVERED\t%s\t%s\t%s\n' "$DEVICE_SID" "$tty" "$usbProps"
		((discovered_count += 1))
	done

	return 0
}

device_bind_usb_to_service() {
	local sid="$1"
	local tty="$2"
	local device_path="$3"
	local usbProps

	test -e "/dev/$tty" \
		|| { echo "Error: tty ($tty) does not exist" >&2; return 1; }

	[[ $(serial_device_installer_get_available_devices $tty) != $tty ]] \
		&& { echo "Error: tty ($tty) is not available" >&2; return 1; }

	serial_device_installer_fill_usb_props $tty $DEFAULT_USB_PROPS usbProps
	serial_device_installer_set_device_sid $usbProps

	[[ $sid != $DEVICE_SID ]] && {
		echo "Error: Device changed" >&2 ; return 1; }

	# get dbus values
	local service_name=
	dbus_common_get_value "${dbus_available_devices_prefix}/${device_path}/ServiceName" service_name

	# fill serial-starter-installer variables
	DEVICE_UDEV_PROPS="${usbProps}"
	DEVICE_TTY="${tty}"
	DEVICE_SERVICE_NAME="${service_name}"

	serial_device_installer_install 1>/dev/null || return 1

	printf 'DEVICE:CLAIMED\t%s\n' "$DEVICE_SID"
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
	case "${1:-}" in
		remove)
			shift
			if [[ "${2:-}" == "all" ]]; then
				shift
				device_remove_all
			fi
			device_remove "${1:-}";;
		scan)
			shift
			device_scan_usb;;
		bind)
			shift
			device_bind_usb_to_service "$@";;
		*)
			if [[ -n ${1:-} ]]; then
				echo "device: invalid command : ${1}" >&2
			fi
			;;
	esac
fi
