#!/bin/bash

# shellcheck disable=SC2317,SC2329  # Don't warn about unreachable commands in this file

set -o nounset

declare __this_path;__this_path=$(dirname "${BASH_SOURCE[0]}")

. "$__this_path/../opkg-common"

__validate_package_name() {
  if [[ -z "$1" ]]; then
    log_error "package_commond: package name not supplied"
    return 1
  fi
  return 0
}

__package_set_install_lock() {
	mkdir -p /var/lock/
	touch /var/lock/opkg-manager-install
}
__package_clear_install_lock() {
	rm -f /var/lock/opkg-manager-install
}

__package_command() {
	local action_msg="${1}"

  shift 1 # rest are opkg args

  __init_root_fs_for_writing

	local this_path; this_path=$(dirname "${BASH_SOURCE[0]}")
	"$this_path/packages_helper" update force # update packages and json

	__cleanup() {
		__package_clear_install_lock
		opkg_common_clear_requested_package_update
	}
	trap '__cleanup' RETURN

	__package_clear_install_lock
  __package_set_install_lock

  opkg "$@"
	local -i status=$?

	__package_clear_install_lock

	opkg_common_package_update_requested && {
		opkg_common_clear_requested_package_update
		"$this_path/packages_helper" update force # update packages and json
	}

  __restore_previous_fs_access

	if [[ $status == 0 ]]; then
    log  "$action_msg succeeded"
  else
    log "$action_msg failed (status $status)"
  fi

  return $status
}

# Helper to install a package and log output/errors
package_install() {
  local package_name="$1"

  __validate_package_name "${package_name}" || return

  log "Installing $*"
  __package_command "Install" install "$@"

}
__status_message() {
  local status="${1}"
  local action="${2}"
  if [[ $status == 0 ]]; then
    log  "$action succeeded"
  else
    log "$action failed (status $status)"
  fi
}
package_upgrade() {
  local package_name="$1"

  __validate_package_name "${package_name}" || return

  log "Upgrading $*"

  __package_command "Upgrade" upgrade "$@"

}

package_remove() {
  local package_name="$1"

  __validate_package_name "${package_name}" || return

  if [[ -z $(opkg list-installed "${package_name}") ]]; then
    log "Not Installed ${package_name}, exiting"
    return 0
  fi

  log "Removing $*"
  __package_command "Remove" remove "$@"

}

case "${1:-}" in
  install)
    shift
    package_install "$@"
    ;;
  remove)
    shift
    package_remove "$@"
    ;;
  upgrade)
    shift
    package_upgrade "$@"
    ;;
  *)
    if [[ -n ${1:-} ]]; then
      echo "package: incorrect command : ${1}" >&2
    fi
    ;;
esac
