#!/usr/bin/env bash

PACKAGE_GUI_V2_PLUGIN_NAME="Inetbox"
PACKAGE_DEVICE_KEY="Inetbox"
PACKAGE_DEVICE_SERVICE_NAME="dbus-inetbox"
PACKAGE_DEVICE_DISPLAY_NAME="Inetbox"

PACKAGE_CUSTOM_OVERVIEW_PAGES=(InetboxOverview)
PACKAGE_CUSTOM_MENUS=(PageSettings/InetboxPageSettingsSubMenu)

PACKAGE_DBUS_SETTINGS=

# shellcheck source=/data/dev/addons/opkg-manager/src/data/opkg-manager/source-common
source "${VE_ROOT_PATH:-}/data/opkg-manager/source-common"
addsource install-helper "$@"
