#!/bin/bash
 
declare package_name="themer"

. "${VE_ROOT_DIR:-}/data/opkg-manager/opkg-common"

opkg_common_register_package "${package_name}"

. /data/themer/themer-common
themer_common_patch_files

echo "successfully installed ${package_name}"

