#!/bin/bash

declare package_name="themer"

. "${VE_ROOT_DIR:-}/data/opkg-manager/opkg-common"

opkg_common_unregister_package "${package_name}"

. /data/themer/themer-common
themer_common_remove_patch_from_files

echo "successfully removed ${package_name}"
