#!/usr/bin/env bash

dry_run=

__this_path="$(dirname "${BASH_SOURCE[0]}")"

if [[ -f "$__this_path/../opkg-manager/libs/log-lib" ]]; then
  # shellcheck disable=SC1091
  . "$__this_path/../opkg-manager/libs/log-lib"
else
  . "$__this_path/../../../../opkg-manager/src/data/opkg-manager/libs/log-lib"
fi

readonly mount_common_path="${VENUS_ROOT_DIR:-}/data/mount-shares"
readonly mountpoint_conf_file="${mount_common_path}/mountpoints.conf"
declare -i mount_point_ping_tries=10

# exposed so can override for mocking
# overriding read callin bashdb fails
__mount_common___read() {
  # shellcheck disable=SC2162
  read "$@"
}

__mount_common_is_server_up() {
  local -i count=0
  local server="${1}"

  while ((count < mount_point_ping_tries)); do
    if ping -q -c1 -W 3 "${server}" >>/dev/null; then
      return 0
    fi
    ((count += 1))
  done

  return 1
}


__validate_host_and_path() {
 
  local input="$1"
  local path octet host
  local host_error="ERROR: host name or ip address is invalid"
  local host_path_error="ERROR: host path is invalid"
 
  # Split host and path
  #strip leading // to make it easier.
  [[ "${input:0:2}" == "//" ]] && input="${input:2}"
  [[ "${input:0:1}" == "/" ]] && {  log_error "$host_error"; return 1; }

  if [[ "$input" == */* ]]; then
    host="${input%%/*}"
    path="${input#*/}" 
  else
    host="$input"
    path=""
  fi
 
  if [[ "$host" =~ ^([0-9]{1,3}\.) ]]; then
    if [[ "$host" =~ ^[0-9]+(\.[0-9]+){3}$ ]]; then
      # ---------- Strict IPv4 ---------
      IFS='.' read -r o1 o2 o3 o4 <<<"$host"
      for octet in "$o1" "$o2" "$o3" "$o4"; do
        [[ "$octet" =~ ^[0-9]+$ ]] || { log_error "$host_error"; return 1; }
        ((octet >= 0 && octet <= 255)) || { log_error "$host_error"; return 1; }
      done
    else
      log_error "$host_error"
      return 1
    fi
 
  # ---------- Hostname / DNS ----------
  elif [[ ! "$host" =~ ^([a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)(\.([a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?))*$ ]]; then
    log_error "$host_error"
    return 1
  fi
 
  # ---------- Path validation ----------
  if [[ -n "$path" ]]; then
    [[ "$path" =~ ^[^\/\\:?*"<>|.$][^\/\\:?*"\<\>|$]{0,254}$ ]] || { 
      log_error "$host_path_error"
      return 1; } 
  else
    log_error "$host_path_error"
    return 1
  fi

  return 0
}

__validate_mount_settings() {
  
  local type="${1}"
  #local username="${2}";local password="${3}"
  local hostpath="${4}"
  local mountpoint="${5}"
  #local options="${6}"
 
  (($# < 6)) && {
    log_error "ERROR: invalid arguments passed"
    return 1
  }
  [[ -z "$type" ]] || [[ "$type" != "cifs" ]] && {
    log_error "ERROR: invalid mount type: $type"
    return 1
  }
  [[ -z "$hostpath" ]] && {
    log_error "ERROR: host_path is required"
    return 1
  }
  [[ -z "$mountpoint" ]] && {
    log_error "ERROR: mount_point is required"
    return 1
  }
 
  __validate_host_and_path "$hostpath" || return 1
 
  if [[ -n "$mountpoint" ]]; then
    [[ "$mountpoint" =~ ^/([A-Za-z0-9._-]+/)*[A-Za-z0-9._-]+/?$ ]] || { 
      log_error "ERROR: mountpoint path is invalid"; return 1; } 
  fi
}

__hostname_from_server_path_byref() {
  local -n __serverPath="${1}"
  [[ "${__serverPath:0:2}" == "//" ]] && __serverPath="${__serverPath:2}"
  __serverPath="${__serverPath%%/*}"
}


__update_mount_settings() {
  local -n _mount_settings="${1}"
  local name="${_mount_settings%%|*}"
  
  [[ -f "${mountpoint_conf_file}" ]] || {
    mkdir -p "$(dirname "${mountpoint_conf_file}")"
    echo "${_mount_settings}" >> "${mountpoint_conf_file}"
    return 0
  }

  # if a line starting with the name is found then replace the line
  # else add to the end
  if grep -q ^"${name}|" "${mountpoint_conf_file}"; then
    sed -i "/^${name}/c${mount_settings}" "${mountpoint_conf_file}"
  else
    echo "${mount_settings}" >>"${mountpoint_conf_file}"
  fi

}

##############################################
# checks if the supplied mountpoint is available
# each check is every .5 seconds
# Args
# {1} mount point: [reqiured] the mount point directory to check
# {2} tries: [optional] the number of tries before returning 
#     with a failure. The default is 10 tries (5 seconds aprox)
mount_common_wait_on_mount_point() {
  
  local mount_point="${1}"
  local -i count=0 tries="${2:-10}"
  local -i quiet=0
  [[ "${2:-}" == "--quiet" || "${3:-}" == "--quiet" ]] && quiet=1

  while ((count < tries)); do 
    mountpoint -q "$mount_point" && {
      ((quiet==0)) && log_error "mountpount available: ${1}"
      return 0
      };
    sleep .5
    ((count+=1))
  done
  
  ((quiet==0)) && log_error "mountpount not available: ${1}"
  return 1
}

# reads the mountpoint_conf_file and remounts
# the share
# no args
mount_common_mount_all() {

  log "mount_all"

  if [[ ! -f ${mountpoint_conf_file} ]]; then
    log "missing mountpoint.conf file"
    return 0
  fi

  log_push_indent

  local name type username password source target options
  local -i mount_found
  
  while IFS= read -r line || [ -n "$line" ]; do
    [[ -z "$line" || "$line" == [[:blank:]#]* ]] && continue

    IFS='|' read -r name type username password source target options <<< "$line"
    # call in backbround thread
    (mount_common_mount_server "$type" "$username" "$password" "$source" "$target" "$options" &) &&
      mount_found=1  
 
  done <"${mountpoint_conf_file}"

  if [[ ! ${mount_found} ]]; then
    log "no mount points found in mountpoints.conf"
  fi

  log_pop_indent

  log "mount_all done"

  return 0
}

#############################################################################
# Creates a cifs mount point using the passed arguments
#  Version 1.0
#  Arguments:
#  {1} type     | [required] The type of mountpoint. Currently must be set to "cifs"
#  {2} source   | [required] The source (server host and path) of the mountpoint. i.e. //192.168.2.1/data or //hostname/data
#  {3} target   | [required] The local target directory for the mountpoint. i.e. /mnt/data
#  {4} username | [optional] The user name to access the source.
#  {5} password | [optional] The password used to access the source.
#  {6} options  | [optional] Any additional options. i.e. ",someoption -rw"
#############################################################################
mount_common_mount_server() {

  log "mount_server"

  local type="${1}"
  local username="${2}"
  local password="${3}"
  local host_name_path="${4}"
  local mount_point="${5}"
  local options="${6:-}"
 
  __validate_mount_settings "${type}" "${username}" "${password}" \
    "${host_name_path}" "${mount_point}" "${options}" || return 1
  
  local host="${host_name_path%%/*}"
  __hostname_from_server_path_byref host

  # if mountpoint returns anything else but 0 then re-mount (-q=quiet)
  if mountpoint -q "${mount_point}"; then
    log "mount point already exists"
    return 0
  fi

  log_push_indent

  log "not mounted...mounting"
  
  __mount_common_is_server_up "${host}" || {
    
    log_error "ERROR: server is down: ${host}"
    return 1
  }
  
  log "server ${host} is up"
  log "mounting... ${host_name_path} to ${mount_point}"

  if [[ ! -d "${mount_point}" ]]; then
    log "creating mountpoint folder... ${mount_point}"
    if [[ ! ${dry_run} ]]; then
      mkdir -p "${mount_point}" || {
        log_error "Unable to create mountpount folder"
        return 1
      }
    fi
  else
    log "mountpoint folder already exists... ${mount_point}"
  fi
 
  if [[ ! ${dry_run} ]]; then
    local -i retval=0
    
    # append // to host name/ip if missing
    [[ "${host_name_path:0:2}" != "//" ]] && host_name_path="//${host_name_path}"
    
    # append command to options if missing
    [[ -n "${options}" && "${options:0:1}" != "," ]] && options=",${options}"

    # make sure $options is next to $password
    # shellcheck disable=SC2140
    mount -t "${type}" -o user="${username}",pass="${password}${options}" "${host_name_path}" "${mount_point}" || {
      retval=$?;
      log_error "ERROR: mount returned exit code $retval" ;
      return $retval; }
  fi
 
  log_pop_indent

  log "mount server done"

  return 0
}

#############################################################################
# Creates a cifs mount point and stores the settings to the
# mountpoints.conf file.
#if any arguments are missing (-s,-t,-u,-p) the values are prompted for.
#  Version 1.0
#  Arguments:
#    --source | -s : The source of the mountpoint. i.e. //192.168.2.1/data or //hostname/data
#    --target | -t : The local target for the mountpoint. i.e. /mnt/data
#    --username | -u: The user name to access the source.
#    --password | -p : The password used to access the source.
#    --options  | -o : any additional options. i.e. ",someoption -rw"
#############################################################################
mount_common_mount_cifs() {

  printhelp() {
    cat <<EOF

if any arguments are missing (-s,-t,-u,-p) the values are prompted for.

  Version 1.0

  Arguments:
    --source | -s : The source of the mountpoint. i.e. //192.168.2.1/data or //hostname/data
    --target | -t : The local target for the mountpoint. i.e. /mnt/data
    --username | -u: The user name to access the source.
    --password | -p : The password used to access the source.
    --options  | -o : any additional options. i.e. ",someoption -rw"
EOF

  }

  local name=
  local source=
  local target=
  local username=
  local password=
  local options=
  local mount_settings=
  local prompt_options=
  while [ $# -gt 0 ]; do
    case "$1" in
    --name* | -n*)
      [[ "$1" != *=* ]] && shift
      name="${1#*=}"
      ;;
    --source* | -s*)
      [[ "$1" != *=* ]] && shift
      source="${1#*=}"
      ;;
    --target* | -t*)
      [[ "$1" != *=* ]] && shift
      target="${1#*=}"
      ;;
    --username* | -u*)
      [[ "$1" != *=* ]] && shift
      username="${1#*=}"
      ;;
    --password* | -p*)
      [[ "$1" != *=* ]] && shift
      password="${1#*=}"
      ;;
    --options* | -o)
      [[ "$1" != *=* ]] && shift
      options="${1#*=}"
      ;;
    --help | -h)
      printhelp
      exit 0
      ;;
    *)
      >&2 printf "Error: Invalid argument\n"
      exit 1
      ;;
    esac
    shift
  done
  
  [[ -z "${name}" ]] && __mount_common___read -r -p "Enter the name for the mount point: " name
  [[ "${name}" =~ ^[A-Za-z0-9_]+$ && "${name}" =~ [A-Za-z0-9] ]] || {
    log_error "ERROR: Invalid name: Only alpha numeric characters with underscores allowed"; return 1; }

  [[ -z "${target}" ]] && prompt_options=1
  [[ -z "${source}" ]] && __mount_common___read -r -p "Enter server ip/host address and path: " source
  [[ -z "${target}" ]] && __mount_common___read -r -p "Enter local mount point folder: " target
  [[ -z "${username}" ]] && __mount_common___read -r -p "Enter username for share: " username
  [[ -z "${password}" ]] && __mount_common___read -r -s -p "Enter password for share: " password

  if [[ -z "${source}" ]] || [[ -z "${target}" ]]; then
    log_error "ERROR: required args missing"
    return 1
  fi
  # options may often be empty so check use prompt_options based off of target

  ((prompt_options)) && __mount_common___read -r -p "Enter any custom options: " options
 
  # validate before adding to mountpoint_conf_file
  local type="cifs"

  __validate_mount_settings "${type}" "${username:-}" "${password:-}" \
    "${source}" "${target}" "${options:-}" || return 1

  mount_common_mount_server "${type}" "${username:-}" "${password:-}" \
    "${source}" "${target}" "${options:-}" && {

      mount_settings="${name}|${type}|${username}|${password}|${source}|${target}|${options}"

      log "adding mount to mountpoints.conf"
      if [[ ! ${dry_run} ]]; then
        __update_mount_settings mount_settings
      fi
  
    }
 
}

mount_common_remove_mount()
{
  [[ -f "${mountpoint_conf_file}" ]] || return 0
  
  local mount_name="${1}"
  sed -i "/^${mount_name}/d" "${mountpoint_conf_file}"
 
  return 0
}


case "${1:-}" in
  mount_server)
    shift
    mount_common_mount_server "$@"
    ;;
  mount-cifs)
    shift
    mount_common_mount_cifs "$@"
    ;;
  mount-all)
    shift
    mount_common_mount_all
    ;;
  waitformount)
    shift
    mount_common_wait_on_mount_point "$@"
    ;;
  *)
    [[ -n "${1:-}" ]] && echo "invalid command: ${1:-}"
    ;;
esac
