#!/bin/bash
 
declare package_name="dbus-inetbox"
#VE_SERVICE_MAPPING_NAME="neshunt"
#TTY_FILE="/data/${SERVICE_NAME}/serial-starter.devname"
#SERIAL_STARTER_RULE_FILE="/data/${SERVICE_NAME}/serial-starter.rule"
#DBUS_MESSAGE_PATH="" #"com.victronenergy.packageManager /GuiEditStatus"

source "${VENUS_ROOT_DIR:-}/data/opkg-helpers/opkg-common"
opkg_common_register_package "${package_name}"

source "${VENUS_ROOT_DIR:-}/data/opkg-helpers/serial-device-installer"
serial_device_installer_install && serial_device_installer_start_service

echo "${package_name} installed"

