#!/bin/bash
#
# Start script for dbus-nu-shunt
#   First parameter: tty device to use
#
# Keep this script running with daemon tools. If it exits because the
# connection crashes, or whatever, daemon tools will start a new one.
#
# Arguments
# -d -debug  : debug logging
# -s -serial : serial port such as ttyACM0

tty=${1}
[[ -z $tty || ! -e "/dev/$tty" ]] && { echo "ERROR:invalid TTY:$tty"; exit 1; }

sdi_rule_id=$(udevadm info --query=property --name="/dev/$tty" | sed -n "s/^SDI_RULE_ID=//p")

declare _this_path=$(dirname "${BASH_SOURCE[0]}")
app="${_this_path}/../src/opt/victronenergy/dbus-inetbox/__main__.py"
#app="${_this_path}/../src-orig/opt/victronenergy/dbus-inetbox/__main__.py"

echo "path=${_this_path}"

python $app -s "/dev/$tty" -i "$sdi_rule_id"
