#!/bin/bash

declare package_name="$(basename "${0%.*}")" #get file name without path
declare service_name="$package_name"
 
source "${VENUS_ROOT_DIR:-}/data/opkg-helpers/opkg-common"
opkg_common_register_package "${package_name}"

source "${VENUS_ROOT_DIR:-}/data/opkg-helpers/serial-device-installer"
serial_device_installer_install && serial_device_installer_start_service

echo "${package_name} installed"
