#!/bin/bash
# shellcheck disable=SC2317,SC2329  # Don't warn about unreachable commands in this file

set -o nounset

declare _this_path; _this_path=$(dirname "${BASH_SOURCE[0]}")
source "$_this_path/../opkg-common"
 
case "${1:-}" in
  add)
	feed_editor "add" "${2:-}" "${3:-}" "${4:-}"
		;;
  edit)
		feed_editor "edit" "${2:-}" "${3:-}" "${4:-}"
		;;
  remove)
		feed_editor "remove" "${2:-}" "" ""
		;;
  set)
    opkg_common_set_feed "${2:-}"
		;;
  type)
		feed_get_feed_type
		;;
	*)
		if [[ -n ${1:-} ]]; then
			echo "feed: incorrect command : ${1}" >&2
		fi
		;;
esac
