#!/bin/bash

# dbus-common: Functions for managing dbus settings for Venus OS themes

set -o nounset

# Function: dbus_common_add_dbus_settings
# Adds dbus settings for a group.
# Arguments:
#   $1 - group name (string)
#   $2 - dbus_settings (string, lines formatted as name:type:min:max:value)
# type should be: 'i' (integer), 'f' (float) and 's' (string)
# Each line in dbus_settings is parsed and sent to dbus as a setting.
dbus_common_add_dbus_settings() {

	local servicePath="com.victronenergy.settings"
	local group name
	local dbus_settings="$1"

	# For each line in dbus_settings, parse fields and add setting
	while IFS=: read -r fullpath type min max value; do
		# Skip blank lines and comments, including lines with leading whitespace.
		fullpath="${fullpath#"${fullpath%%[![:space:]]*}"}"
		[[ -z "$fullpath" || "$fullpath" == \#* ]] && continue
 
  	group="${fullpath%/*}"
    name="${fullpath##*/}"
		# Trim any leading whitespace from group
		group="${group#"${group%%[![:space:]]*}"}"
 
		echo "adding dbus setting: $group/$name, value:$value, type:$type, min:$min, max:$max"
		dbus -y $servicePath /Settings AddSetting $group "$name" "$value" "$type" $min $max 1>/dev/null
	done <<< "$dbus_settings"
}

 # Function: dbus_common_remove_dbus_settings
 # Removes dbus settings for a group.
 # Arguments:
 #   $1 - group name (string)
 #   $2 - dbus_settings (string, lines formatted as just name or name:type:min:max:value) 
 # Removes all settings listed in dbus_settings for the group.
 dbus_common_remove_dbus_settings() {
	local baseService="com.victronenergy.settings"
	local dbus_settings="$1"
	local prev_group=""
	local names=""

	while IFS=: read -r fullpath _ _ _ _; do
		# Skip blank lines and comments, including lines with leading whitespace.
		fullpath="${fullpath#"${fullpath%%[![:space:]]*}"}"
		[[ -z "$fullpath" || "$fullpath" == \#* ]] && continue
		group="${fullpath%/*}"
		name="${fullpath##*/}"
		# Trim any leading whitespace from group
		group="${group#"${group%%[![:space:]]*}"}"

		if [[ -n "$prev_group" && "$group" != "$prev_group" ]]; then
			echo "removing values $names from /Settings/$prev_group"
			dbus -y $baseService /Settings/$prev_group RemoveSettings "%[$names]"
			names=""
		fi

		[[ -z "$names" ]] && names="'$name'" || names+=", '$name'"
		prev_group="$group"
	done <<< "$dbus_settings"

	if [[ -n "$names" && -n "$prev_group" ]]; then
		echo "removing values $names from /Settings/$prev_group"
		dbus -y $baseService /Settings/$prev_group RemoveSettings "%[$names]"
	fi
}

 # Function: dbus_common_add_remove_debus_settings
 # Adds or removes dbus settings for the Themer group.
 # Arguments:
 #   $1 - remove flag (integer, 1 to remove, 0 to add)
 # Uses __themer_command_get_dbus_settings to get settings.
 dbus_common_add_remove_dbus_settings() {
	
	local -i remove=${1}
  local settings="${2}"
	if ((remove)); then
		dbus_common_remove_dbus_settings "$settings"
	else
		dbus_common_add_dbus_settings "$settings"
	fi
}

if [[ "${1:-}" == "dbus-remove-settings" ]]; then
  shift
	dbus_common_remove_dbus_settings "$1"
elif [[ "${1:-}" == "dbus-add-settings" ]]; then
  shift
	dbus_common_add_dbus_settings "$1"
fi
 