#!/usr/bin/env bash

set -o nounset
 
# set package name using the path of the calling file's location

declare PACKAGE_NAME="${PACKAGE_NAME-$(basename "$(dirname "${BASH_SOURCE[1]-}")")}"
declare RESTART_GUI_SERVICE="${RESTART_GUI_SERVICE:=0}"
declare DBUS_SETTINGS="${DBUS_SETTINGS-}"
declare RC_LOCAL_SCRIPT="${RC_LOCAL_SCRIPT-}"
 
__appendDataDir() {
	local VENUS_DATA_DIR="/data/dev/utils/opkg-manager/src"; [ -d $VENUS_DATA_DIR ] || VENUS_DATA_DIR=
  local file="${1}"
	local -n _out_dir=${2}
	_out_dir="${VENUS_DATA_DIR:-}/data/opkg-manager/${file}"
}
# List of special pages (without .qml)
__load_source_file() {
		# may require symlink to /data/dev 
  local source_file=
	__appendDataDir "${1}" source_file
	[[ -f ${source_file} ]] || { echo "ERROR: source file does not exist:${source_file}" >&2; exit 1; }

	set -- # resets $1, $2, ...
	
	# shellcheck disable=SC1090
	. "${source_file}"
	
}

install_helper_add_remove_dbus_csv_items() {
	
	local cvs_string=
	local command="$1"
  local dbusPath="$2"
	shift 2
 
	dbus_common_get_value "${dbusPath}" cvs_string
 
	__install_helper_add_remove_comma_delimited_string "$command" cvs_string "$@" 

	# TODO UPDATE
	dbus_common_set_string_value <<< "{'path':'${dbusPath}', 'default': '${cvs_string}'}"
}

install_helper_add_remove_custom_service_path() {
	
	local -a service_paths=()

	__get_custom_service_paths_from_dbus_settings_byref service_paths
 
	install_helper_add_remove_dbus_csv_items "$1" "OpkgManager/AvailableCustomServices" "${service_paths[@]}" 

}

__get_custom_service_paths_from_dbus_settings_byref() {
	local -n _out_paths="$1"
	local -A seen_paths=()
	local line=
	local service_path=

	_out_paths=()

	while IFS= read -r line; do
		[[ "$line" =~ Settings/OpkgManager/CustomServices/([^/]+)/ProductName(:|$) ]] || continue
		service_path="${BASH_REMATCH[1]}"
		[[ -z "$service_path" || -n "${seen_paths[$service_path]:-}" ]] && continue
		seen_paths["$service_path"]=1
		_out_paths+=("$service_path")
	done <<< "${DBUS_SETTINGS:-}"
}

# function: __install_helper_add_remove_comma_delimited_string
# adds or removes any item from a command delimited string
# arg1: 
#				The command, "add|remove"
# arg2: (byref)
#				The comma delimited string
# arg3: 
#				The items to add|remove from the string
__install_helper_add_remove_comma_delimited_string() {
	local command="${1}"
	local -n _csv_string="${2}"
	shift 2
	local item
	local -a cur_items=()
	local -a result=()

	IFS=',' read -ra cur_items <<< "${_csv_string}"

	if [[ "${command}" == "add" ]]; then
		local -A _seen=()
		for item in "${cur_items[@]}"; do
			[[ -z "${item}" ]] && continue
			[[ -v _seen["${item}"] ]] && continue
			_seen["${item}"]=1
			result+=("${item}")
		done
		for item in "$@"; do
			[[ -v _seen["${item}"] ]] && continue
			_seen["${item}"]=1
			result+=("${item}")
		done
	elif [[ "${command}" == "remove" ]]; then
		local -A _remove=()
		for item in "$@"; do
			_remove["${item}"]=1
		done
		local -A _seen=()
		for item in "${cur_items[@]}"; do
			[[ -z "${item}" ]] && continue
			[[ -v _remove["${item}"] ]] && continue
			[[ -v _seen["${item}"] ]] && continue
			_seen["${item}"]=1
			result+=("${item}")
		done
	fi

	local IFS=','
	_csv_string="${result[*]-}"
}

# arguments {1} (optional): set to remove to remove
install_helper_add_remove_patch() {
	local remove=0
	[[ "${1:-}" == "remove" ]] && remove=1
	
	for patchfile in "$installer_path"/*.patch; do
		RESTART_GUI_SERVICE=1
		if ((remove==0)); then
			file_patcher_apply_patch "$patchfile"
		else
			file_patcher_revert_patch "$patchfile"
		fi
	done
}

install_helper_post_install() {

  [[ -z "$PACKAGE_NAME" ]] && { echo "ERROR: PACKAGE_NAME not set"; return 1; }

	local installer_path
	installer_path="$(dirname "${BASH_SOURCE[1]}")"

	__load_source_file "opkg-common"
	__load_source_file "dbus-common"

	echo "registering package: $PACKAGE_NAME"
	opkg_common_register_package "$PACKAGE_NAME"

	[[ -n "${RC_LOCAL_SCRIPT:-}" ]] &&
		opkg_common_add_script_to_rc_local "${RC_LOCAL_SCRIPT}"
	
	(
		echo "patching files"
		
		__load_source_file "file-patcher"
		shopt -s nullglob #required to ensure if no .patch files exists,
											# patchfile is not filled with the path instead
		for patchfile in "$installer_path"/*.patch; do
			file_patcher_apply_patch "$patchfile"
		done
	)
 
	echo "adding dbus settings"

	[[ -n "${DBUS_SETTINGS_DEPRECIATED:-}" ]] &&
		dbus_common_remove_settings <<< "$DBUS_SETTINGS_DEPRECIATED"
 
	[[ -n "${DBUS_SETTINGS:-}" ]] && {
		dbus_common_add_settings <<< "$DBUS_SETTINGS"
		install_helper_add_remove_custom_service_path "add"
	}
	
	install_helper_restart_gui_service
	return 0
}
 
install_helper_pre_remove() {
 
	[[ -z "$PACKAGE_NAME" ]] && { echo "ERROR: PACKAGE_NAME not set"; return 1; }
	
	local installer_path; 
	installer_path="$(dirname "${BASH_SOURCE[1]}")"

	__load_source_file "opkg-common"
 	__load_source_file "dbus-common"
 
	[[ -n "${RC_LOCAL_SCRIPT:-}" ]] &&
		opkg_common_remove_script_from_rc_local "${RC_LOCAL_SCRIPT}"
 
	opkg_common_unregister_package "$PACKAGE_NAME"

	(
		__load_source_file "file-patcher"
		install_helper_add_remove_patch remove
	)
	
	echo "removing dbus settings"

	[[ -n "${DBUS_SETTINGS:-}" ]] && {
		dbus_common_remove_settings <<< "$DBUS_SETTINGS"
		install_helper_add_remove_custom_service_path "remove"
	}

	[[ -n "${DBUS_SETTINGS_DEPRECIATED:-}" ]] &&
		dbus_common_remove_settings <<< "$DBUS_SETTINGS_DEPRECIATED"

	install_helper_restart_gui_service
	return 0
}

install_helper_restart_gui_service() {
	((RESTART_GUI_SERVICE)) || return

	echo "restarting gui service..."
  svc -t /service/gui
}
 