#!/usr/bin/env bash

set -o nounset

readonly rc_local_file="${VENUS_ROOT_DIR:-}/data/rc.local"
readonly opkg_helpers_path="${VENUS_ROOT_DIR:-}/data/opkg-manager"
readonly opkg_registered_packages_file="/data/conf/registered-packages.conf"
# shellcheck disable=SC2034
readonly opkg_rc_local_d_dir="${opkg_helpers_path}/rc.local.d"
readonly resize2fs_file="/opt/victronenergy/swupdate-scripts/resize2fs.sh"

OPKG_MANAGER_FEED_NAME="opkg-manager"
OPKG_MAIN_FEED_NAME="thespinmaster"
OPKG_MAIN_FEED_PATH="main"

OPKG_FEED_PATH="${VENUS_ROOT_DIR:-}/etc/opkg"
OPKG_FEED_LOCAL_CONFIG_FILE="/data/conf/opkg-manager-release.conf"
OPKG_FEED_CONFIG_FILE="${OPKG_FEED_PATH}/opkg-manager.conf"
OPKG_FEED_BASE_URL="https://github.com/${OPKG_MAIN_FEED_NAME}/venus-os/raw/refs/heads/main/feeds/release"

# OPKG_VENUS_VERSION=
 
___is_fs_readonly=
init_opkg_helpers=
dry_run=

declare __this_path; __this_path="$(dirname "${BASH_SOURCE[0]}")"
. "${__this_path}/libs/log-lib"

# Expand rootfs and make it writable
opkg_common_expand_root_fs() {
  
  log "expanding root fs"
  if [ ! $dry_run ]; then
    $resize2fs_file
  fi
}

# mount the rootfs as read/write
__root_fs_readwrite() {
  log "mounting fs as read write"
  if [ ! $dry_run ]; then
    mount -o remount,rw /
  fi
}

# mount the rootfs as read/write
__mount_root_fs_readonly() {
  log "mounting fs as readonly"

  if [ ! $dry_run ]; then
    mount -o remount,ro /
  fi

}

# pass initial state of ___is_fs_readonly
# if initial state is empty but ___is_fs_readonly now
# has a value then we restore back to readonly.
__restore_previous_fs_access() {
  
  log "restoring previous fs state"

  if [[ "${___is_fs_readonly}" = 1 ]]; then
    __mount_root_fs_readonly
  else
    log "previous state was readwrite; nothing to restore"
  fi
  ___is_fs_readonly=
  
}

opkg_common_ensure_feeds() {

  log "ensure opkg feed"
 
  local feed_manager="src/gz ${OPKG_MANAGER_FEED_NAME} ${OPKG_FEED_BASE_URL}/${OPKG_MANAGER_FEED_NAME}"

  if [[ ! -f "${OPKG_FEED_LOCAL_CONFIG_FILE}" ]]; then
    echo "$feed_manager" > "${OPKG_FEED_LOCAL_CONFIG_FILE}" 

    local feed_main="src/gz ${OPKG_MAIN_FEED_NAME} ${OPKG_FEED_BASE_URL}/${OPKG_MAIN_FEED_PATH}"
    echo "$feed_main" >> "${OPKG_FEED_LOCAL_CONFIG_FILE}" 
 
  elif ! grep -q "$feed_manager" "$OPKG_FEED_LOCAL_CONFIG_FILE"; then
    echo "$feed_manager" >> "${OPKG_FEED_LOCAL_CONFIG_FILE}" 
  fi
 
  log "creating opkg feed symlink"
  ln -sf "$OPKG_FEED_LOCAL_CONFIG_FILE" "$OPKG_FEED_CONFIG_FILE"
 
}

opkg_common_get_venus_verion_byref() {
  local -n __version="${1}"

  if [ -f "/opt/victronenergy/version" ]; then
    __version="$(cat /opt/victronenergy/version | head -n 1)"
  else
    __version=""
  fi
}

__wait_for_opkg() {
  local -i counter=0
  while [ -e /run/opkg.lock ]; do
    sleep 0.5
    ((++counter))
    ((counter>30)) && return 1
  done
  return 0
}

opkg_common_update_packages() {
  (
    __wait_for_opkg && opkg update 
  ) &
  
  local opkg_pid=$!
  wait "$opkg_pid"
  return 0
}
 
opkg_common_remove_feed_symlink() {
  if [ -L "${OPKG_FEED_CONFIG_FILE}" ]; then
    rm "${OPKG_FEED_CONFIG_FILE}"
  fi
}

__ensure_rc_local() {
  log_trace "__ensure_rc_local"
  if [[ ! -f "${rc_local_file}" ]]; then
    log "rc.local does not exist; creating..."
    if [[ ! $dry_run ]]; then
      touch "${rc_local_file}"  
    fi
  fi
  if [[ ! $dry_run ]]; then
    chmod +x "${rc_local_file}"
  fi
}

# placed in separate function: easier to override for testing
__is_fs_readonly() {
  grep -q "[[:space:]]ro[[:space:],]" /proc/mounts
}

# sets the rootfs for writing
# sets the flag ___is_fs_readonly
__init_root_fs_for_writing() {

  log "__init_root_fs_for_writing"

  if [[ -z "${___is_fs_readonly}" ]]; then

    # make sure the file system is writeable
    if __is_fs_readonly; then
      ___is_fs_readonly=1
    else
      ___is_fs_readonly=0
    fi
 
    if [[ "${___is_fs_readonly}" = 1 ]]; then
      __root_fs_readwrite
    fi

    log "fs is readonly:${___is_fs_readonly}"

  else
    log "___is_fs_readonly already initialized"
  fi

}

# ensures the opkg feed is setup
# calls opkg update
# sets init_opkg_helpers flag so
# only done once
__init_opkg() {

  ((init_opkg_helpers)) && {
    log "__init_opkg: already initialzed"
    return;
  }

  log "__init_opkg: initializing"

  opkg_common_ensure_feeds
  if [ ! $dry_run ]; then
    opkg update
  fi

  init_opkg_helpers=1
 
}

__opkg_common_try_install_package() {

  log "__opkg_common_try_install_package"

  local package_name="${1:-}"

  if [[ -z "${package_name}" ]]; then
    log "package name not supplied"
    return 1
  fi

  # see if the ipk is installed
  # list-installed only returns an exact match
  local installed; installed=$(opkg list-installed "${package_name}")

  # if already installed then exit
  if [[ -n "${installed}" ]]; then
    log "Already Installed ${package_name}, exiting"
    return 0
  fi

  __init_root_fs_for_writing
  __init_opkg

  log "Installing... ${package_name}"
  if [ ! $dry_run ]; then
    opkg install "${package_name}"
  fi
}

# ensures the rc.local.d folder exists
# {1} [in,out]: in, a number between 0 and 99,
#               out the full path to the folder
opkg_common_ensure_rc_local_d() {
  local -n __path="${1}"
  if [[ "$__path" -ge 0 ]] && [[ "$__path" -le 99 ]]; then 
    mkdir -p "${opkg_rc_local_d_dir}/${__path}" && {
        __path="${opkg_rc_local_d_dir}/${__path}"
      return 0
    }
  else
    log_error "ERROR: invalid arg. arg1 should be a number between 0 and 99"
  fi
  return 1
}

# loops through all the lines in
# the opkg_registered_packages_file 
# and proceeds to install each
# package.
# takes care of read write access
opkg_common_ensure_installed() {

  [[ -f "$opkg_registered_packages_file" ]] || {
     log "opkg_registered_packages_file does not exist"; return 0; }

  log "opkg_common_ensure_installed"
 
  log_push_indent
  local isfirst=1

  while IFS= read -r line
  do
    # ignore comments and empty lines
    [[ -z "${line//[[:space:]]/}" || $line == \#* ]] && continue
    
    if (( isfirst == 1 )); then
      isfirst=0
    else
      sleep 1
    fi
 
    __wait_for_opkg
    
    __opkg_common_try_install_package "${line}"

  done < "${opkg_registered_packages_file}"

  __restore_previous_fs_access

  log_pop_indent

  log "opkg_common_ensure_installed: done"

  return 0
}
 
# adds script to the rc_local file
# args: ${1} the script to add
# this script can be multiple lines
opkg_common_add_script_to_rc_local() {

  [[ -z "${1:-}" ]] && { log_error "ERROR: no script supplied" ; return 1; }

  __ensure_rc_local
  
  local thispath; thispath="$(dirname "${BASH_SOURCE[0]}")"
  . "$thispath/libs/string-lib"

  #local found=
  #string_lib_multiline_find_replace "${1}" --find-only --break-on-first < "$rc_local_file"
  local found; found=$(string_lib_multiline_find_replace "${1}" --find-only --break-on-first < "$rc_local_file")
  
  if [[ -z $found ]]; then
    log "adding custom script to ${rc_local_file}"
    if [ ! $dry_run ]; then
      echo "${1}" >> "${rc_local_file}"
    fi
  else
    log "custom script already added"
  fi
  return 0
}

# removes the script from the rc_local file
# args: ${1} the script to add
# this script can be multiple lines
opkg_common_remove_script_from_rc_local() {

  [[ -z "${1:-}" ]] && { log_error "ERROR: no script supplied" ; return 1; }
  [[ -f "${rc_local_file}" ]] || return 0

  log "removing custom script from ${rc_local_file}"

  # reads from ${rc_local_file} removes ${1} and saves back to ${rc_local_file}
  # string_lib_multiline_find_replace "${1}" --trim-lines < "${rc_local_file}" > "${rc_local_file}"

  if [ ! $dry_run ]; then
  
  thispath="$(dirname "${BASH_SOURCE[0]}")"
  . "$thispath/libs/string-lib"
    
    # TODO add inplace option to string_lib_multiline_find_replace
    local tmp; tmp=$(mktemp)
    string_lib_multiline_find_replace "${1}" --trim-lines < "${rc_local_file}" > "$tmp" && {
      mv "$tmp" "${rc_local_file}"
    }
     
  fi

}

# adds an opkg package name to the custom packages file
# the custom packages file is read when a new firmware
# has been installed
# args: ${1} the name of the package
opkg_common_register_package() {

  [[ -z "${1:-}" ]] && { log_error "ERROR: no package name supplied" ; return 1; }

  local package_name="${1:-}"
  
  if [[ ! -f "${opkg_registered_packages_file}" ]] || ! grep -q "^${package_name}$" "${opkg_registered_packages_file}" ; then
    log "adding ${package_name} to ${opkg_registered_packages_file}"
    if [ ! $dry_run ]; then
      echo "${package_name}" >> "${opkg_registered_packages_file}"
    fi
  else
    log "package ${package_name} already added"
  fi

}

# removes an opkg package name to the custom packages file
# args: ${1} the name of the opkg package to remove
opkg_common_unregister_package() {

  [[ -z "${1:-}" ]] && { log_error "ERROR: no package name supplied" ; return 1; }
  [[ -f "${opkg_registered_packages_file}" ]] || return 0

  local package_name="${1:-}"

  if grep -q "^${package_name}$" "${opkg_registered_packages_file}" ; then
    log "Removing ${package_name} from ${opkg_registered_packages_file}"
    if [ ! $dry_run ]; then
      sed -i "/^$package_name/d" "${opkg_registered_packages_file}"
    fi
  else
    log "package '${package_name}' not found"
  fi

}

case "${1:-}" in
  opkg_common_ensure_installed)
    if [[ "${2:-}" == "--dry-run" ]]; then
      dry_run=1
      log "*** DRY RUN ***"
    fi
    opkg_common_ensure_installed
    ;;
 
  ensure-feeds)
    opkg_common_ensure_feeds
    ;;
  remove-feed-symlink)
    opkg_common_remove_feed_symlink
    ;;
esac
