#!/usr/bin/env bash
 
: ' 
  WHEN UDEVADM_PROPS empty THEN
    detect usb using usb monitor
        fills TTY (done __fill_prop_values_from_tty_when_not_headless)
        from TTY fill UDEVADM_PROPS (done __fill_props_from_tty)
  OTHERWISE
      find USB_DEVPATH from UDEVADM_PROPS
      find TTY from USB_DEVPATH
'
set -o nounset

__this_path="$(dirname "${BASH_SOURCE[0]}")"
. "$__this_path/libs/log-lib"
 
# requires: SERVICE_NAME
# optional: SERVICE_MAPPING_NAME
# args_byref service_mapping_name
__get_service_mapping_name_byref() {
  local -n _service_mapping_name="${1}"
  _service_mapping_name="${SERVICE_MAPPING_NAME:-}"

  [[ -z "${_service_mapping_name}" ]] && {
    _service_mapping_name="ve_${SERVICE_NAME//-/_}"
    _service_mapping_name="${_service_mapping_name//./_}"
  }
}

# requires: UDEVADM_PROPS
# args_byref props
# args_byref count_of_filled
__count_of_filled_props_byref() {
  local -n _out_props=${1}
  local -n _count_of_filled=${2}
  _count_of_filled=0
  for key in "${!_out_props[@]}"; do
    [[ ${key:0:1} == "+" ]] && continue
    [[ -n "${_out_props[$key]}" ]] && (( _count_of_filled+=1 ))
  done
  return 0
}

# requires: UDEVADM_PROPS
# args_byref props
# optional args_byref count
__are_all_prop_values_filled() {
  local -n _out_props=${1}
  local -n count=${2:--1}
  ((count==-1)) && 
    __count_of_filled_props_byref count

  (( count = "${#_out_props[@]}" )) && return 0
  return 1
}

 
# requires vars: UDEVADM_PROPS
# required args: props_byref
__read_props_byref() {
 
  local -n _out_props="$1";
  local -a __props
  local -A new_props
  local key value
 
  # Split the string into array by NUL character
  IFS='|' read -r -a __props <<< "$UDEVADM_PROPS"
  for key_value in "${__props[@]}"; do
    k="${key_value%%=*}"; 
    value=
    [[ "$key_value" == *"="* ]] && value="${key_value#*=}"
    [[ "$k" =~ ^[a-zA-Z0-9_+]+$ ]] || { echo "UDEVADM_PROPS are invalid" >&2; return 1; }
 
    new_props["$k"]="$value"
  done
  
  # array was loaded without any erros so unset 
  # the origional values and add the new ones
  for k in "${!_out_props[@]}"; do unset "_props[$k]"; done
  for k in "${!new_props[@]}"; do 
     _out_props["$k"]="${new_props[$k]}"; 
  done

  return 0
}
 
# requires vars: UDEVADM_PROPS
__write_props() {
  # shellcheck disable=SC2178
  local -n _props=$1
  local k=
  local key
 
  UDEVADM_PROPS=""
  for k in "${!_props[@]}"; do
    UDEVADM_PROPS+="$k=${_props[$k]}"$'|'
  done
  [[ "${UDEVADM_PROPS:(-1)}" == $'|' ]] &&
    UDEVADM_PROPS="${UDEVADM_PROPS::-1}"

}

# requires vars: UDEVADM_PROPS
# args = {1} tty
# args = {2} in,out props
__fill_props_from_tty() {
  
  local tty="${1}"
  [[ -z "${tty}" ]] && { echo "ERROR: TTY not set;" >&2; return 1; }

  # shellcheck disable=SC2178
  local -n __props=${2}

  local props_to_grep=""
  __prepare_props_for_grep_byref __props props_to_grep
  
  usb_info_lines=$(udevadm info --name="/dev/${tty}" --query=property | grep -E "${props_to_grep}")
  
  local key value
  local -i filled_count=0
  while IFS= read -r line; do
    key="${line%%=*}"
    value="${line#*=}"
    [[ -z "${key}" ]] && continue
    __props["${key}"]="${value}"
    ((filled_count+=1))
  done <<<"${usb_info_lines}"
 
  return 0
}
 
# args: in byref props
# args: {2} out byref props_to_grep
__prepare_props_for_grep_byref() {
  # shellcheck disable=SC2178
  local -n __props="${1}"
  local -n __props_to_grep="${2}"
  local k key_for_regex
  for k in "${!__props[@]}"; do
    key_for_regex="${k//+/\\+}"
    __props_to_grep+="${key_for_regex}=|"
  done
  __props_to_grep=${__props_to_grep::-1}
}

#args: {1} dev_path, {2} byref out tty
__get_tty_paths() {
  local -n _out=$1
  _out=(/sys/class/tty/ttyUSB* /sys/class/tty/ttyACM*)
}

__tty_device_exists() {
  [[ -e "/dev/${1}" ]] && return 0
}

# args: in byref props
# args: {2} out byref tty
__get_tty_from_props_byref() {

  local -n _props="${1}"
  local -n out_tty="${2}"
  local usb_dev_path
  local -i count_of_filled_props=0 count_of_matched_props=0
  local -i usb_def_path_index=0 found_index=-1
  local props_to_compare
  local -a tty_paths=(); __get_tty_paths tty_paths
  local props_to_grep="DEVPATH|"
  
  out_tty=

  __prepare_props_for_grep_byref _props props_to_grep
  __count_of_filled_props_byref _props count_of_filled_props
 
  for dev in "${tty_paths[@]}"; do
    [ -e "$dev" ] || continue
 
    props_to_compare=$(udevadm info -q property -p "$dev" | grep -E "${props_to_grep}")
 
    local key value
 
    while IFS= read -r line; do
      [[ $line =~ ^DEVPATH=* ]] && {
        usb_dev_path=${line#*=}; continue; }
 
      key="${line%%=*}"; value="${line#*=}"
      [[ -z "${key}" ]] && continue
      [[ "${_props[${key}]:-}" == "${value}" ]] && ((count_of_matched_props+=1))
    done <<<"${props_to_compare}"
 
    ((count_of_filled_props==count_of_matched_props)) && {
      ((found_index+=1))

      ((found_index==usb_def_path_index)) && break;
    }
    usb_dev_path=

  done
  
  if  [[ $usb_dev_path ]]; then
    # shellcheck disable=SC2034
    out_tty=$(basename "$usb_dev_path")
    return 0
  fi

  echo "ERROR: tty device does not exist" >&2
  return 1
}
 

# requires vars: SERVICE_NAME, 
# optional vars: SERVICE_MAPPING_NAME, SERIAL_STARTER_SDI_RULE
# required arg1 (byref in) array of usb props
# required arg2 (byref out) the serial_starter_rule 
# required arg3 (byref out) the serial_starter_rule_comment comment
__create_serial_starter_rule_byref() {

  log_trace

  [[ $# -lt 3 ]] && { log_error "ERROR: missing args"; return 1; }

  local -n _props="${1}"
  local -n out_serial_starter_rule="${2}"
  local -n out_serial_starter_rule_comment="${3}"
  local service_mapping_name
  local kv
  local rules=""

  [[ -z "${SERVICE_NAME:-}" ]] && { log_error "ERROR: SERVICE_NAME not set"; return 1; }

  __get_service_mapping_name_byref service_mapping_name

  for kv in "${!_props[@]}"; do
    [[ "${kv}" == "ID_BUS" ]] && continue
    [[ "${kv}" == "+SDI_RULE_ID" || "${kv}" == "SDI_RULE_ID" ]] && continue
    [[ -z "${_props[$kv]}" ]] && continue

    if [[ "${kv:0:1}" == "+" ]]; then
      rules+="ENV{${kv:1}}=\"${_props[$kv]}\", "
    else
      rules+="ENV{${kv}}==\"${_props[$kv]}\", "
    fi
  done

  log_trace "udevadm matches ${rules}"
  if [[ -z "${rules}" ]]; then
    log_error "ERROR: No UDEVADM_PROPS values set."
    return 1
  fi

  if [[ -z "${SERIAL_STARTER_SDI_RULE:-}" ]]; then
    # a 4 bit hex value
    SERIAL_STARTER_SDI_RULE=$(od -An -N2 -tx2 /dev/urandom | tr -d ' \n') || {
      log_error "ERROR creating SERIAL_STARTER_SDI_RULE"
      return 1
    }
  fi

  rules+="ENV{SDI_RULE_ID}=\"${SERIAL_STARTER_SDI_RULE}\", "
  rules+="ENV{VE_SERVICE}=\"${service_mapping_name}\""
  rules="ENV{ID_BUS}=\"usb\", ${rules}"

  if [[ -n "${_props[+SDI_RULE_ID]:-}" || -n "${_props[SDI_RULE_ID]:-}" ]]; then
    out_serial_starter_rule_comment="# sdi rule id:${SERIAL_STARTER_SDI_RULE}: ${SERVICE_NAME}"
  else
    out_serial_starter_rule_comment="# sdi ${SERVICE_NAME}"
  fi

  out_serial_starter_rule="ACTION==\"add\", ${rules}"

  log_trace "new SERIAL_STARTER_RULE=${out_serial_starter_rule}"

  return 0
}

# requires vars: SERIAL_STARTER_RULES_FILE, SERIAL_STARTER_RULES_TEXT_MATCH, SERVICE_NAME
# required args: {1}= serial_starter_rule
# required args: {2}= serial_starter_rule_comment
__add_rule_to_serial_starter_rules_file() {

  log_trace

  local serial_starter_rule="${1}"
  local serial_starter_rule_comment="${2:-}"

  [[ -z "${serial_starter_rule}" ]] && { log_error "ERROR: serial starter rule not set"; return 1; }
  [[ -f "${SERIAL_STARTER_RULES_FILE}" ]] || {
    log_error "ERROR: file not found, SERIAL_STARTER_RULES_FILE:${SERIAL_STARTER_RULES_FILE}"
    return 1
  }
  
  if grep -qF "${serial_starter_rule}" "${SERIAL_STARTER_RULES_FILE}"; then
    log "✓ Serial starter rule already exists in the file."
    return 0
  fi

  local rule_with_comment="${serial_starter_rule_comment}"$'\n'"${serial_starter_rule}"$'\n'
 
  [[ -z "${SERIAL_STARTER_RULES_TEXT_MATCH}" ]] && {
    # add rule to the end of the file
    echo "${rule_with_comment}" >> "${SERIAL_STARTER_RULES_FILE}"
    return 0
  }

  log "Adding new rule to serial starter rules file..."
  log_trace "after line ending:${SERIAL_STARTER_RULES_TEXT_MATCH}"
  
  local -i _found=
  local new_rules="" nl=$'\n'
 
  while IFS= read -r line || { [[ -n "$line" ]]; }; do
    new_rules+="${line}${nl}"
    ((_found)) && continue
    if [[ "$line" = *"${SERIAL_STARTER_RULES_TEXT_MATCH}" ]]; then
      new_rules+="${nl}${rule_with_comment}"
      _found=1
    fi
  done <"${SERIAL_STARTER_RULES_FILE}"

  ((!_found)) && {
    log_error "ERROR: SERIAL_STARTER_RULES_TEXT_MATCH: insert location not found"
    return 1
  }

  echo "${new_rules}" >"${SERIAL_STARTER_RULES_FILE}" || {
    log_error "ERROR adding rule to ${SERIAL_STARTER_RULES_FILE}" 
    return 1
  }
  log "✓ Rule added successfully."
  return 0
}

# required vars: SERIAL_STARTER_CONFIG_FILE, SERVICE_MAPPING_NAME, SERVICE_NAME
__add_ve_service_config_file_mapping() {

  log_trace
 
  [[ -f "$SERIAL_STARTER_CONFIG_FILE" ]] || {
    log_error "ERROR: file not found SERIAL_STARTER_CONFIG_FILE:$SERIAL_STARTER_CONFIG_FILE"
    return 1
  }

  local service_mapping_name; __get_service_mapping_name_byref service_mapping_name
 
  #Try to allign with existing services
  #18=24 - 8 = 16; (24 is mapping offset - 8 for 'service ' len)
  local -i spaces_len; spaces_len=$((16 - "${#service_mapping_name}"))
  ((spaces_len < 1)) && spaces_len=1

  local spaces; spaces=$(head -c "$spaces_len" </dev/zero | tr '\0' ' ')
  local entry="service ${service_mapping_name}${spaces}${SERVICE_NAME}"
  local find_pattern="^[[:space:]]*service[[:space:]]+${service_mapping_name}[[:space:]]+${SERVICE_NAME}[[:space:]]*$"

  if ! grep -Eq "${find_pattern}" "${SERIAL_STARTER_CONFIG_FILE}"; then
    local tmp
    tmp=$(mktemp) || {
      log_error "ERROR: could not create temp file"
      return 1
    }

    {
      printf '%s\n' "${entry}"
      cat "${SERIAL_STARTER_CONFIG_FILE}"
    } >"$tmp" || {
      rm -f "$tmp"
      log_error "ERROR: could not update ${SERIAL_STARTER_CONFIG_FILE}"
      return 1
    }

    mv "$tmp" "${SERIAL_STARTER_CONFIG_FILE}" || {
      rm -f "$tmp"
      log_error "ERROR: could not replace ${SERIAL_STARTER_CONFIG_FILE}"
      return 1
    }

    log "✓ Successfully added ve service mapping config to ${SERIAL_STARTER_CONFIG_FILE}"
  else
    log "✓ ve service mapping already exists"
  fi
}
 
# validates: SERVICE_NAME, UDEVADM_PROPS, SERIAL_STARTER_RULES_FILE, SERIAL_STARTER_CONFIG_FILE
__validate_all() {
 
  [[ -z "${SERVICE_NAME:-}" ]] && {
    log_error "ERROR: SERVICE_NAME not set"
    return 1
  }
  [[ -z "${UDEVADM_PROPS:-}" ]] && {
    log_error "ERROR: UDEVADM_PROPS not set"
    return 1
  }
 
  [[ -f "${SERIAL_STARTER_RULES_FILE:-}" ]] || {
    log_error "ERROR: file not found, SERIAL_STARTER_RULES_FILE:$SERIAL_STARTER_RULES_FILE"
    return 1
  }
  [[ -r "${SERIAL_STARTER_RULES_FILE:-}" ]] || {
    log_error "ERROR: SERIAL_STARTER_RULES_FILE does not have read access:$SERIAL_STARTER_RULES_FILE"
    return 1
  }
  [[ -w "${SERIAL_STARTER_RULES_FILE:-}" ]] || {
    log_error "ERROR: SERIAL_STARTER_RULES_FILE does not have write access:$SERIAL_STARTER_RULES_FILE"
    return 1
  }

  [[ -f "${SERIAL_STARTER_CONFIG_FILE:-}" ]] || {
    log_error "ERROR: file not found, SERIAL_STARTER_CONFIG_FILE:$SERIAL_STARTER_CONFIG_FILE"
    return 1
  }
  [[ -r "${SERIAL_STARTER_CONFIG_FILE:-}" ]] || {
    log_error "ERROR: SERIAL_STARTER_CONFIG_FILE does not have read access:$SERIAL_STARTER_CONFIG_FILE"
    return 1
  }
  [[ -w "${SERIAL_STARTER_CONFIG_FILE:-}" ]] || {
    log_error "ERROR: SERIAL_STARTER_CONFIG_FILE does not have write access:$SERIAL_STARTER_CONFIG_FILE"
    return 1
  }
}

###################################################
# public methods
###################################################
# required vars: SERVICE_NAME, UDEVADM_PROPS, 
#                SERIAL_STARTER_RULES_FILE, SERIAL_STARTER_CONFIG_FILE
#                SERIAL_STARTER_START_SERVICE_PATH, SERVICE_PATH
# optional vars: TTY, SERVICE_MAPPING_NAME, USE_UDEVADM_MONITOR,
#                SERIAL_STARTER_RULES_TEXT_MATCH, USB_TIMEOUT
serial_device_installer_install() {
  
  __validate_all || return 1
  
  local tty; 
  local -A props; __read_props_byref props || return 1
  local -i count; __count_of_filled_props_byref props count || return 1

  if ((count==0)); then
    [[ $(type -t callback_get_tty_port) == function ]] && {
      callback_get_tty_port tty || return 1
    }
    if [[ -n ${TTY:-} && -e /dev/${TTY:-} ]]; then
      tty=$TTY
    else
      echo "ERROR: cannot get tty" >&2
      return 1
    fi
    __fill_props_from_tty "$tty" props || return 1
    __count_of_filled_props_byref props count || return 1
 
    (( count==0 )) && {
      echo "ERROR: no UDEVADM_PROPS found" >&2; return 1; }

    # This is a warning so we continue but log to stderr
    ((count!=${#__props[@]}  ))  && {
      echo "WARNING: not all UDEVADM_PROPS found" >&2; } 

    __write_props props

  elif [[ -n ${TTY:-} && -e /dev/${TTY:-} ]]; then
    tty=$TTY
  else
     __get_tty_from_props_byref props tty
  fi

  log "Installing USB serial device..."
 
  local serial_starter_rule serial_starter_rule_comment
  __create_serial_starter_rule_byref props serial_starter_rule serial_starter_rule_comment || return 1

  __add_rule_to_serial_starter_rules_file "${serial_starter_rule}" "${serial_starter_rule_comment}" || return 1

  __add_ve_service_config_file_mapping || return $?
  
  TTY=$tty
  
  # clear the cache?: /data/var/lib/serial-starter/$tty
  # clear the lock? : /var/lock/serial-starter/$tty

  # reload udm
  serial_device_installer_refresh_udevadm "add"
  
  return 0
}

################################################
# updates udevadm for a usb device
# required vars: TTY
# required arg 1: "add" if adding a device; "remove" if removing
################################################
serial_device_installer_refresh_udevadm() {
  local action="${1}"
  [[ -z "${TTY}" ]] && { log_error "ERROR: TTY not set"; return 1; }
  [[ -z "${action}" ]] && { log_error "ERROR: action arg not not supplied"; return 1; }
  [[ "${action}" != "add" && "${action}" != "remove" ]] && {
     log_error "ERROR: invalid action. should be 'add' or 'remove'"; return 1; }
 
  udevadm control --reload
  udevadm trigger --action=$action /sys/class/tty/$TTY
}


################################################
# removes a serial starter rule from the serial-starter.rules file (/etc/udev/rules.d/serial-starter.rules)
# required vars: SERIAL_STARTER_RULES_FILE, either SERIAL_STARTER_SDI_RULE or TTY must be set
################################################
serial_device_installer_remove_rule() {
  log_trace
 
  [[ -f "${SERIAL_STARTER_RULES_FILE:-}" ]] || {
    log_error "ERROR: file not found, SERIAL_STARTER_RULES_FILE:${SERIAL_STARTER_RULES_FILE}"
    return 1
  }
 
  if [[ -z "${SERIAL_STARTER_SDI_RULE:-}" ]]; then
    [[ -z "${TTY:-}" ]] && { log_error "ERROR: TTY variable not set"; return 1; }
 
    local -A props
    props["SDI_RULE_ID"]=""
    __fill_props_from_tty "$TTY" props || { log_info "Cannot find SDI_RULE_ID, nothing to do"; return 0; }
    SERIAL_STARTER_SDI_RULE="${props[SDI_RULE_ID]:-}"

    [[ -z "${SERIAL_STARTER_SDI_RULE:-}" ]] && { log_info "Cannot find SDI_RULE_ID, nothing to do"; return 0; }
  fi

  local tmp
  tmp="$(mktemp)" || return 1

  sed \
    -e "\|^[[:space:]]*# sdi rule id:${SERIAL_STARTER_SDI_RULE}:.*$|d" \
    -e "\|ENV{SDI_RULE_ID}=\"${SERIAL_STARTER_SDI_RULE}\"|d" \
    "${SERIAL_STARTER_RULES_FILE}" | sed \
    -e '/^$/N;/^\n$/D' > "$tmp" || {
      rm -f "$tmp"
      return 1
    }

  if ! cmp -s "${SERIAL_STARTER_RULES_FILE}" "$tmp"; then
    mv "$tmp" "${SERIAL_STARTER_RULES_FILE}"
    local file_name="$(basename "${SERIAL_STARTER_RULES_FILE}")"
    log "✓ Successfully removed rule from ${file_name}"
  else
    rm -f "$tmp"
  fi

  return 0
}

################################################
# Removes the rule added to the serial-starter.rules file
# Removes the service mapping from the serial-starter.conf file
# Sets TTY var to empty
# required vars: SERIAL_STARTER_CONFIG_FILE, SERVICE_NAME
# optional vars: SERVICE_MAPPING_NAME
################################################
serial_device_installer_remove_service_mapping() {
 
  log_trace

  [[ -f "${SERIAL_STARTER_CONFIG_FILE}" ]] || {
    log_info "serial starter conf file not found"
    return 2
  }

  local service_mapping_name; __get_service_mapping_name_byref service_mapping_name
  
  pattern="^[[:space:]]*service[[:space:]]\+${SERVICE_MAPPING_NAME}[[:space:]]\+${SERVICE_NAME}[[:space:]]*$"

  tmp=$(mktemp)
  sed "/$pattern/d" "$SERIAL_STARTER_CONFIG_FILE" >"$tmp"

  local log_info="\'service ${service_mapping_name} ${SERVICE_NAME}\' in $SERIAL_STARTER_CONFIG_FILE"
  if cmp -s "$SERIAL_STARTER_CONFIG_FILE" "$tmp"; then
    log "ve service mapping not found:${log_info}"
    rm "$tmp"
  else
    mv "$tmp" "$SERIAL_STARTER_CONFIG_FILE"
    log "✓ Sucessfully removed ve service mapping:${log_info}"
  fi
}
################################################
# Add a file (ttyACME) to /dev/serial-starter/
# this file is picked up by the serial-starter
# and starts the service.
# Requires variables:
# TTY, SERVICE_NAME, SERIAL_STARTER_START_SERVICE_PATH
################################################
serial_device_installer_start_service() {
 
  log_trace
 
  [[ -d "${SERIAL_STARTER_START_SERVICE_PATH}" ]] || {
    log_error "ERROR: SERIAL_STARTER_START_SERVICE_PATH not set or does not exist"
    return 1
  }
  [[ -z "${SERVICE_NAME}" ]] && {
    log_error "ERROR: SERVICE_NAME not set"
    return 1
  }

  if [[ -z "$TTY" ]]; then 
    local -A props; __read_props_byref props || return 1
    __get_tty_from_props_byref props tty || return 1
  else
    __tty_device_exists $TTY || { log_error "ERROR: TTY device does not exist"; return 1; }
  fi
 
  log "starting service ${SERIAL_STARTER_START_SERVICE_PATH}/${SERVICE_NAME}.${TTY}"
  
  # make sure there is not a stuck lock in place
  rm -f "/var/lock/serial-starter/${TTY}"
  rm -f "/run/lock/serial-starter/${TTY}"

  touch "${SERIAL_STARTER_START_SERVICE_PATH}/${TTY}"
  return 0
}


# arguments: tty, <property name>
serial_device_installer_get_usb_prop() {
    udevadm info --query=property --name="$1" | sed -n "s/^$2=//p"
}

__ensure_TTY_from_TTY_or_SERIAL_STARTER_SDI_RULE() {
 
  if [[ -z "$TTY" ]]; then
    serial_device_installer_TTY_from_SdiRuleId && return 0
  fi 

  __tty_device_exists "${TTY}" || { log_error "ERROR: TTY device does not exist"; return 1; }
  return 0
}

# Finds and sets the TTY variable from 
# the Serial Starter Rule Id (SERIAL_STARTER_SDI_RULE)
# required vars: SERIAL_STARTER_SDI_RULE
serial_device_installer_TTY_from_SdiRuleId() {
  local -A props; props["SDI_RULE_ID"]=${SERIAL_STARTER_SDI_RULE}
  __get_tty_from_props_byref props tty && TTY=$tty
}

# requires SERIAL_STARTER_CONFIG_FILE
serial_device_installer_service_name_from_tty() {
  local ve_service
  local service_name

  ve_service=$(serial_device_installer_get_usb_prop "$TTY" "VE_SERVICE")
  [[ -z "${ve_service}" ]] && { log_error "ERROR: VE_SERVICE not found"; return 1; }

  service_name=$(grep -E "^service[[:space:]]+${ve_service}[[:space:]]+" "${SERIAL_STARTER_CONFIG_FILE}" | sed -n '1p')
  SERVICE_NAME=${service_name##* }

  [[ -z "${SERVICE_NAME}" ]] && {
    log_error "ERROR: Service name not found for VE_SERVICE:${ve_service}"
    return 1
  }
  return 0 
}

#########################################
# Stops the service using the serial port
# removes the directory /SERVICE_PATH/SERVICE_NAME.TTY
# Requires variables: TTY or SERIAL_STARTER_SDI_RULE
# optional variables: SERVICE_PATH SERVICE_NAME
#########################################
serial_device_installer_stop_and_remove_service() {

  ################################################
  # Stop the service
  # Reads the tty name from the serial-starter.devname
  # file and combines it with the SERVICE_NAME to make
  # the full service name i.e. dbus-ne-shunt.ttyACM0
  ################################################
  log_trace
 
  [[ -z "${SERVICE_PATH:-}" ]] && SERVICE_PATH="/service"
  [[ -d "${SERVICE_PATH}" ]] || { log_error "ERROR: SERVICE_PATH not found"; return 1; }
 
  __ensure_TTY_from_TTY_or_SERIAL_STARTER_SDI_RULE || return 1
  if [[ -z "${SERVICE_NAME:-}" ]]; then
    serial_device_installer_service_name_from_tty || return 1
  fi

  local full_service_path="${SERVICE_PATH}/${SERVICE_NAME}.${TTY}"
  log_trace "full_service_path=${full_service_path}"

  if [ -d "${full_service_path}" ]; then
    log "stopping service ${full_service_path}"
    svc -d "${full_service_path}" 2>/dev/null
    sleep 3 # secs
    rm -RF "${full_service_path}" 2>/dev/null
  else
    log_error "ERROR: could not find service: ${full_service_path}"
    return 1
  fi

}
 
################################################################
################################################################
 