#!/usr/bin/env bash

RESTART_GUI_SERVICE=1

PACKAGE_CUSTOM_MENUS=(PageSettingsDisplay/ThemerPageSettingsSubMenu)

DBUS_AVAILABLE_THEMES="Dark" # space separated list of themes
PACKAGE_DBUS_SETTINGS="
		{'path':'/Settings/Themer/AvailableThemes', 'default':'Dark'}
	  {'path':'/Settings/Themer/CurrentTheme', 'default':''}
		{'path':'/Settings/Themer/Themes/Dark/TextColor', 'default':'#ffffff'}
		{'path':'/Settings/Themer/Themes/Dark/WindowBackgroundColor', 'default':'#202020'}
		{'path':'/Settings/Themer/Themes/Dark/BackgroundColor', 'default':'#202020'}
		{'path':'/Settings/Themer/Themes/Dark/BackgroundColorSelected', 'default':'#4790d0'}
		{'path':'/Settings/Themer/Themes/Dark/BackgroundColor2', 'default':'#313131'}
		{'path':'/Settings/Themer/Themes/Dark/IconSuffixNormal', 'default':'-active'}
		{'path':'/Settings/Themer/Themes/Dark/IconSuffixSelected', 'default':'-active'}
		{'path':'/Settings/Themer/Themes/Dark/BorderColor', 'default':'#3c3c3c'}
		{'path':'/Settings/Themer/Themes/Dark/ServiceBackgroundColor', 'default':'#b07c04'}
		{'path':'/Settings/Themer/Themes/Dark/BackgroundColorSelected', 'default':'#2969a1'}
		{'path':'/Settings/Themer/Themes/Dark/BackgroundTankColor', 'default':'#cccccc'}
		{'path':'/Settings/Themer/Themes/Dark/BackgroundTankColor', 'default':'#cccccc'}
		{'path':'/Settings/Themer/Themes/Dark/Color2', 'default':'#c4c4c4'}
"

#PACKAGE_DBUS_SETTINGS_DEPRECATED=""

RESTART_GUI_SERVICE=1

pre_install() {
	install_helper_add_remove_dbus_csv_items "add" "/Settings/Themer/AvailableThemes" "$DBUS_AVAILABLE_THEMES"
}
pre_remove() {
	install_helper_add_remove_dbus_csv_items "remove" "/Settings/Themer/AvailableThemes" "$DBUS_AVAILABLE_THEMES"
}

# shellcheck source=/data/dev/addons/opkg-manager/src/data/opkg-manager/source-common
source "${VE_ROOT_PATH:-}/data/opkg-manager/source-common"
addsource install-helper "$@"
