#!/usr/bin/env bash

set -o nounset

# set package name using the path of the calling file's location
PACKAGE_NAME="${PACKAGE_NAME-"$(basename "$(dirname "$(realpath "${0}")")")"}"
RESTART_GUI_SERVICE="${RESTART_GUI_SERVICE:=0}"
DBUS_SETTINGS="${DBUS_SETTINGS-}"
RC_LOCAL_SCRIPT="${RC_LOCAL_SCRIPT-}"

[[ ${DEV_INSTALL:-} == 1 ]] && [[ -f /data/dev/utils/opkg-manager/src ]] && 
		export VE_ROOT_PATH=/data/dev/utils/opkg-manager/src
# shellcheck source=/data/dev/utils/opkg-manager/src/data/opkg-manager/source-common
source "${VE_ROOT_PATH:-}/data/opkg-manager/source-common"

install_helper_add_remove_dbus_csv_items() {
	
	local csv_string=
	local command="$1"
  local dbusPath="$2"
	shift 2

	dbus_common_get_value "${dbusPath}" csv_string
 
	__install_helper_add_remove_comma_delimited_string "$command" csv_string "$@" 
	
	if [[ -z "${csv_string}" ]]; then
		dbus_common_remove_settings <<< "{'path':'${dbusPath}'}"
		return 0
	fi

	dbus_common_set_string_value "${dbusPath}" "${csv_string}"
}

install_helper_add_remove_custom_service_path() {
	
	local -a service_paths=()

	__get_custom_service_paths_from_dbus_settings_byref service_paths
 
	install_helper_add_remove_dbus_csv_items "$1" "/Settings/OpkgManager/AvailableCustomServices" "${service_paths[@]}" 

}

__get_custom_service_paths_from_dbus_settings_byref() {
  # shellcheck disable=SC2178 # false positve
	local -n _out_paths="$1" 
	local -A seen_paths=()
	local line=
	local service_path=

	_out_paths=()

	while IFS= read -r line; do
		[[ "$line" =~ Settings/OpkgManager/CustomServices/([^/]+)/ProductName(:|$) ]] || continue
		service_path="${BASH_REMATCH[1]}"
		[[ -z "$service_path" || -n "${seen_paths[$service_path]:-}" ]] && continue
		seen_paths["$service_path"]=1
		_out_paths+=("$service_path")
	done <<< "${DBUS_SETTINGS:-}"
}

# function: __install_helper_add_remove_comma_delimited_string
# adds or removes any item from a command delimited string
# arg1: 
#				The command, "add|remove"
# arg2: (byref)
#				The comma delimited string
# arg3: 
#				The items to add|remove from the string
__install_helper_add_remove_comma_delimited_string() {
	local command="${1}"
	local -n _csv_string="${2}"
	shift 2
	local item
	local -a cur_items=()
	local -a result=()

	IFS=',' read -ra cur_items <<< "${_csv_string}"

	if [[ "${command}" == "add" ]]; then
		local -A _seen=()
		for item in "${cur_items[@]}"; do
			[[ -z "${item}" ]] && continue
			[[ -v _seen["${item}"] ]] && continue
			_seen["${item}"]=1
			result+=("${item}")
		done
		for item in "$@"; do
			[[ -v _seen["${item}"] ]] && continue
			_seen["${item}"]=1
			result+=("${item}")
		done
	elif [[ "${command}" == "remove" ]]; then
		local -A _remove=()
		for item in "$@"; do
			_remove["${item}"]=1
		done
		local -A _seen=()
		for item in "${cur_items[@]}"; do
			[[ -z "${item}" ]] && continue
			[[ -v _remove["${item}"] ]] && continue
			[[ -v _seen["${item}"] ]] && continue
			_seen["${item}"]=1
			result+=("${item}")
		done
	fi

	local IFS=','
	_csv_string="${result[*]-}"
}

# arguments {1} (optional): set to remove to remove
install_helper_add_remove_patch() {
	local remove=0
	local msg=

	if [[ "${1:-}" == "remove" ]]; then
		remove=1
		msg="Reverting patched files"
  else
		msg="Patching files"
	fi
 
	shopt -s nullglob
  
  local installer_path; installer_path="$(dirname "$(realpath "${0}")")"

	for patchfile in "$installer_path"/*.patch; do
		[[ -n "$msg" ]] && { echo "$msg"; msg=; }

		RESTART_GUI_SERVICE=1
		if ((remove==0)); then
			file_patcher_apply_patch "$patchfile"
		else
			file_patcher_revert_patch "$patchfile"
		fi
	done

}

__initialize=0

install_helper_initialize() {
	(( ${__initialize:-0} )) && return
	__initialize=1
	setsource "opkg-common"
	setsource "dbus-common"
	setsource "file-patcher"
	
}

install_helper_post_install() {

  [[ -z "${PACKAGE_NAME:-}" ]] && { echo "ERROR: PACKAGE_NAME not set"; return 1; }
 
	install_helper_initialize
 
	echo "Registering package: ${PACKAGE_NAME}"
	opkg_common_register_package "${PACKAGE_NAME}"

	if [[ -f "/data/${PACKAGE_NAME}/buildtime" ]]; then
		echo "Package build time: $(cat /data/"${PACKAGE_NAME}"/buildtime)"
	fi

	[[ -n "${RC_LOCAL_SCRIPT:-}" ]] &&
		opkg_common_add_script_to_rc_local "${RC_LOCAL_SCRIPT}"

	install_helper_add_remove_patch add
 
  [[ -n "${DBUS_SETTINGS:-}" || -n "${DBUS_SETTINGS_DEPRECIATED:-}" ]] &&
		echo "Adding dbus settings"
		
	[[ -n "${DBUS_SETTINGS_DEPRECIATED:-}" ]] &&
		dbus_common_remove_settings <<< "${DBUS_SETTINGS_DEPRECIATED}"
 
	[[ -n "${DBUS_SETTINGS:-}" ]] && {
		dbus_common_add_settings <<< "${DBUS_SETTINGS}"
		install_helper_add_remove_custom_service_path "add"
	}

	install_helper_restart_gui_service
	return 0
}
 
install_helper_pre_remove() {

	[[ -z "$PACKAGE_NAME" ]] && { echo "ERROR: PACKAGE_NAME not set"; return 1; }
	local action="${1-}"

	install_helper_initialize
 
	[[ -n "${RC_LOCAL_SCRIPT:-}" ]] &&
		opkg_common_remove_script_from_rc_local "${RC_LOCAL_SCRIPT}"
 
	opkg_common_unregister_package "$PACKAGE_NAME"
 
	install_helper_add_remove_patch remove 
	
	if [[ "$action" != "upgrade" ]]; then
		[[ -n "${DBUS_SETTINGS:-}" || -n "${DBUS_SETTINGS_DEPRECIATED:-}" ]] &&
			echo "Removing dbus settings"

		[[ -n "${DBUS_SETTINGS:-}" ]] && {
			dbus_common_remove_settings <<< "$DBUS_SETTINGS"
			install_helper_add_remove_custom_service_path "remove"
		}

		install_helper_restart_gui_service
	fi

	return 0
}

install_helper_restart_gui_service() {
	((RESTART_GUI_SERVICE)) || return
 
	echo "Restarting gui service..."
  #svc -t /service/gui &
	nohup svc -t /service/gui >/dev/null 2>&1 &
}
 