#!/bin/bash

#TEST_USB_ID="1a86:55d3"

SERVICE_NAME=$(basename "${0%.*}") #get file name without path
VE_SERVICE_MAPPING_NAME="neshunt"

#if false; then

################################################
# Add serial starter rule to serial-serter.rules
################################################

INSTALL_HELPER_ACTION="usb-serial-helper.detect_add" #"detect_add" "add" "remove" 
INSTALL_HELPER_SCRIPT_FILE="${0%.*}.install-helper" # strip file extension (.postinst)
SERIAL_STARTER_RULES_FILE="/etc/udev/rules.d/serial-starter.rules"
DBUS_MESSAGE_PATH="" #"com.victronenergy.packageManager /GuiEditStatus"

python "${INSTALL_HELPER_SCRIPT_FILE}"\
    "${INSTALL_HELPER_ACTION}"\
    "${SERIAL_STARTER_RULES_FILE}"\
    "${SERVICE_NAME}"\
    "${VE_SERVICE_MAPPING_NAME}"\
    "${DBUS_MESSAGE_PATH}"
    #"${TEST_USB_ID}"

#fi

################################################
# Add service mapping to serial starter conf file
################################################
SERIAL_STARTER_CONFIG_FILE='/etc/venus/serial-starter.conf'
CONFIG="service ${VE_SERVICE_MAPPING_NAME}"$'\t\t'"${SERVICE_NAME}"
  
if ! grep -q "^${CONFIG}$" "${SERIAL_STARTER_CONFIG_FILE}"; then
  echo "adding service mapping config from ${SERIAL_STARTER_CONFIG_FILE}"
  sed -i '1s/^/'"${CONFIG}"'\n/' $SERIAL_STARTER_CONFIG_FILE
fi
################################################

#fi

################################################
# Adding ensure-installed to rc.local
################################################
RC_LOCAL_FILE="/data/rc.local"
RC_LOCAL_ACTION="/data/${SERVICE_NAME}/ensure-installed"
if ! grep -q "^${RC_LOCAL_ACTION}$" "${RC_LOCAL_FILE}"; then
  echo "adding ${RC_LOCAL_ACTION} to ${RC_LOCAL_FILE}"
  echo "${RC_LOCAL_ACTION}" >> "${RC_LOCAL_FILE}"
  chmod +x "${RC_LOCAL_FILE}"
fi
################################################

echo "${SERVICE_NAME} installed"
