#!/usr/bin/env bash

PACKAGE_CUSTOM_DEVICE_KEY="NeShunt"
PACKAGE_CUSTOM_DEVICE_NAME="dbus-ne-shunt"
PACKAGE_CUSTOM_DEVICE_DISPLAY_NAME="Ne Shunt"

PACKAGE_CUSTOM_OVERVIEW_PAGES=(NeShuntOverview)

PACKAGE_DBUS_SETTINGS=
PACKAGE_DBUS_SETTINGS_DEPRECATED=

# shellcheck source=/data/dev/addons/opkg-manager/src/data/opkg-manager/source-common
source "${VE_ROOT_PATH:-}/data/opkg-manager/source-common"
addsource install-helper "$@"
