#!/usr/bin/env bash
 
RESTART_GUI_SERVICE=1
DBUS_SETTINGS="
		OpkgManager/CustomOverviewPages/OverviewInetbox:s:0:0:''
		OpkgManager/CustomMenus/PageSettings/PageSettingsInetboxSubMenu:s:0:0:''
	"
#todo change to CustomSettingsPagesMenuItems

#	./dbus-common "dbus-add-settings" "OpkgManager/CustomPageSettingsMenuItems/PageSettingsInetboxSubMenu:s:0:0"

 # ./dbus-common "dbus-add-settings" "OpkgManager/CustomOverviewPages/OverviewInetbox:s:0:0"
 # ./dbus-common "dbus-remove-settings" "OpkgManager/CustomOverviewPages/OverviewInetbox:s:0:0"

if [[ "$1" == "dev-install" ]]; then
  VE_ROOT_DIR=/data/dev/utils/opkg-manager/src
fi

source ${VE_ROOT_DIR:-}/data/opkg-manager/install-helper

if [[ "$1" == "install" || "$1" == "dev-install" ]]; then
	install_helper_post_install

  source "${VENUS_ROOT_DIR:-}/data/opkg-manager/serial-device-installer"
  serial_device_installer_install && serial_device_installer_start_service
 
elif [[ "$1" == "remove" ]]; then
	install_helper_pre_remove
fi

# install_helper_finished
