#!/usr/bin/env bash

DBUS_SETTINGS="
		{'path':'/Settings/OpkgManager/CustomOverviewPages/InetboxOverview', 'default':''}
		{'path':'/Settings/OpkgManager/CustomMenus/PageSettings/InetboxPageSettingsSubMenu', 'default':''}
		{'path':'/Settings/OpkgManager/CustomServices/Inetbox/ProductName', 'default':'Inetbox'}
		{'path':'/Settings/OpkgManager/CustomServices/Inetbox/ServiceName', 'default':'dbus-Inetbox'}
"

#use defaults
# {'path':'/Settings/OpkgManager/CustomServices/Inetbox/UsbProps', 'default':'ID_VENDOR,ID_MODEL,ID_SERIAL'}
# {'path':'/Settings/OpkgManager/CustomServices/Inetbox/UsbMappingName', 'default':'inetbox'}

#DBUS_SETTINGS_DEPRECIATED='
#		{'path':'/Settings/Devices/dbus_inetbox/Port'}
#		{'path':'/Settings/Devices/dbus_inetbox/ServiceName'}
#'
 
if [[ "$1" == "dev-install" ]]; then
  VE_ROOT_DIR=/data/dev/utils/opkg-manager/src
fi

# shellcheck source=/data/dev/utils/opkg-manager/src/data/opkg-manager/install-helper
source "${VE_ROOT_DIR:-}/data/opkg-manager/install-helper"

if [[ "${1:-}" == "install" || "${1:-}" == "dev-install" ]]; then
	install_helper_post_install 
elif [[ "${1:-}" == "remove" ]]; then
	install_helper_pre_remove
fi

# install_helper_finished
