#!/usr/bin/env bash

RESTART_GUI_SERVICE=1

DBUS_SETTINGS="
		{'path':'/Settings/OpkgManager/CustomOverviewPages/InetboxOverview', 'default':''}
		{'path':'/Settings/OpkgManager/CustomMenus/PageSettings/InetboxPageSettingsSubMenu', 'default':''}
		{'path':'/Settings/OpkgManager/CustomServices/Inetbox/ProductName', 'default':'Inetbox'}
		{'path':'/Settings/OpkgManager/CustomServices/Inetbox/ServiceName', 'default':'dbus-Inetbox'}
"

#use defaults
# {'path':'/Settings/OpkgManager/CustomServices/Inetbox/UsbProps', 'default':'ID_VENDOR,ID_MODEL,ID_SERIAL'}
# {'path':'/Settings/OpkgManager/CustomServices/Inetbox/UsbMappingName', 'default':'inetbox'}

#DBUS_SETTINGS_DEPRECIATED='
#		{'path':'/Settings/Devices/dbus_inetbox/Port'}
#		{'path':'/Settings/Devices/dbus_inetbox/ServiceName'}
#'
 
# shellcheck source=/data/dev/utils/opkg-manager/src/data/opkg-manager/source-common
source "/data/opkg-manager/source-common"
setsource install-helper

if [[ "${1:-}" == "install" || "${1:-}" == "dev-install" ]]; then
	# shellcheck disable=SC2034
	install_helper_post_install 
elif [[ "${1:-}" == "remove" ]]; then
	install_helper_pre_remove
fi

# install_helper_finished
