#!/usr/bin/env bash

SERVICE_NAME="test-service"

DBUS_SETTINGS="
		{'path':'/Settings/OpkgManager/CustomServices/TestService/ProductName', 'default': 'Test Service'}
		{'path':'/Settings/OpkgManager/CustomServices/TestService/ServiceName', 'default':'test-service'}
"

#DBUS_SETTINGS_DEPRECIATED="
#		{'path':'/Settings/OpkgManager/CustomMenus/PageSettingsDisplay/PageSettingsNeShuntSubMenu'}
#"

pre_install() {
	if [[ $INSTALL_ACTION == "dev-install" ]]; then
		dbus_common_add_settings <<< "${DBUS_SETTINGS}"
		install_helper_add_remove_custom_service_path "add"
		exit 0
	fi
}
pre_remove() {
	if [[ "$1" == "dev-remove" ]]; then
  	echo "dev-install"
		dbus_common_remove_settings <<< "${DBUS_SETTINGS}"
		install_helper_add_remove_custom_service_path "remove"
		exit 0
	fi
}

# shellcheck source=/data/dev/addons/opkg-manager/src/data/opkg-manager/source-common
source "${VE_ROOT_PATH:-}/data/opkg-manager/source-common"
setsource install-helper
