#!/bin/env bash
BUILD_DIR="/data/dev/addons/dbus-inetbox/src-external/gui-v2/v2/Inetbox"

if [[ ! -d "$HOME/dev-local" ]]; then
	echo "dbus-inetbox/build: dev-local not available"
else
	cd "$BUILD_DIR" || exit

	./build-plugin # 192.168.10.24
fi
