#!/bin/bash

set -o nounset
 
declare this_path; this_path="$(dirname "${BASH_SOURCE[0]}")"
 
QML_TARGET_PATH="/opt/victronenergy/gui/qml"
QML_SOURCE_PATH="$this_path/../src${QML_TARGET_PATH}"
 
[[ -d "${QML_TARGET_PATH}" ]] || { echo "Wrong Server! (path not found ${QML_TARGET_PATH})"; exit 1; }
 
QML_ICONS_TARGET_PATH="/opt/victronenergy/themes/ccgx/icons"
QML_ICONS_SOURCE_PATH="$this_path/../src${QML_ICONS_TARGET_PATH}"

QML_PLUGIN_SOURCE_PATH="$QML_SOURCE_PATH/OpkgHelpers"
QML_PLUGIN_TARGET_PATH="$QML_TARGET_PATH/OpkgHelpers"

QML_FILES=(
	
	OpkgManager 

	OpkgHeaderDescriptionItem.qml
	OpkgEditBoxLargeText.qml
	
	PageSettingOpkg.qml
		PageSettingsOpkgPackages.qml
		PageSettingsOpkgPackages.js
			PageSettingsOpkgPackageInstall.qml

	PageSettingsOpkgFeeds.qml
		PageSettingsOpkgFeedEdit.qml
	
	OpkgObjectCustomOverviewPages.qml
	OpkgPageSettingsCustomMenus.qml
	OpkgPageSettingsSubMenu.qml
	
	opkg-utils.js



)
	#MySubMenu.qml
	#MyCustomOverviewPage.qml

# Icons
QML_ICONS_FILES=(
	icon-opkg-manager-tick.svg
  icon-opkg-manager-tick-active.svg
)

for file in "${QML_FILES[@]}"; do
	ln -sf "$QML_SOURCE_PATH/$file" "$QML_TARGET_PATH/$file"
done
 
for icon in "${QML_ICONS_FILES[@]}"; do
	ln -sf "$QML_ICONS_SOURCE_PATH/$icon" "$QML_ICONS_TARGET_PATH/$icon"
done
 
ln -sf "$QML_TARGET_PATH/PageSettings.qml" "$QML_SOURCE_PATH/PageSettings.qml"
 
ln -sf "$this_path/../src/data/opkg-manager/opkg-common" "/data/opkg-manager/opkg-common"
 
echo "done"