#!/bin/bash

set -o nounset

#if [[ -z $(opkg list-installed gui-v2) ]]; then
  #opkg install gui-v2 start-gui-v2
#fi
#if [[ -z $(opkg list-installed qttools-tools) ]]; then
  #opkg install qttools-tools
#fi
#if [[ -z $(opkg list-installed qtbase-tools) ]]; then
  #opkg install qtbase-tools
#fi
#sudo apt-get install -y qt6-l10n-tools linguist-qt6

declare DEVICE_IP_ADDRESS="${1:-}"

compiler_script=~/dev-local/gui-v2/tools/gui-v2-plugin-compiler.py

# Force Qt6 tools to avoid qtchooser wrappers (/usr/bin/lupdate, /usr/bin/rcc).
export PATH="/usr/lib/qt6/bin:/usr/lib/qt6/libexec:${PATH}"

if [[ ! -f "$compiler_script" ]]; then
  echo "/opt/victronenergy/gui-v2/gui-v2-plugin-compiler.py not found" >&2
  exit 1
fi

python3 "$compiler_script" \
    --name Inetbox \
    --min-required-version v1.2.13 \
    --devicelist 0xD01A Inetbox_devicelist_main.qml inetbox_page_title_simple

if [[ -n "${DEVICE_IP_ADDRESS}" ]]; then
  echo "--- copying plugin to device ${DEVICE_IP_ADDRESS}"
  scp Inetbox.json root@"${DEVICE_IP_ADDRESS}":/tmp/Inetbox.json
  ssh root@"${DEVICE_IP_ADDRESS}" 'bash -s' << 'EOF'
mkdir -p /data/apps/available/Inetbox/gui-v2 && \
  cp /tmp/Inetbox.json /data/apps/available/Inetbox/gui-v2/Inetbox.json
mkdir -p /data/apps/enabled && \
  ln -sf /data/apps/available/Inetbox /data/apps/enabled
svc -t /service/flashmq
EOF

fi

mkdir -p ../../../src/data/apps/available/Inetbox
mkdir -p ../../../src/data/apps/enabled
ln -sf /data/apps/available/Inetbox ../../../src/data/apps/enabled
