#!/bin/bash

declare package_name="dbus-inetbox"

source "${VENUS_ROOT_DIR:-}/data/opkg-manager/opkg-common"
opkg_common_unregister_package "${package_name}"

source "${VENUS_ROOT_DIR:-}/data/opkg-manager/serial-device-installer"
serial_device_installer_remove

serial_device_installer_stop_and_remove_service
 
echo "${package_name}" removed
 