#!/usr/bin/env bash

PACKAGE_DEVICE_KEY="TestInstall"
PACKAGE_DEVICE_SERVICE_NAME="test-install"
PACKAGE_DEVICE_DISPLAY_NAME="Test Install"

PACKAGE_DBUS_SETTINGS=

pre_install() {
	if [[ $PACKAGE_ACTION == "dev-install" ]]; then
		install_common_add_custom_device
		exit 0
	fi
}
pre_remove() {
	if [[ "$PACKAGE_ACTION" == "dev-remove" ]]; then
  	echo "dev-install"
		install_common_remove_custom_device
		exit 0
	fi
}

# shellcheck source=/data/dev/addons/opkg-manager/src/data/opkg-manager/source-common
source "${VE_ROOT_PATH:-}/data/opkg-manager/source-common"
addsource installer-common "$@"
