#!/bin/bash

#depends on timeout

printhelp() {
  cat <<EOF
Detects and returns the port name (ttyXXXX) when a new usb device is plugged in.

  Version 1.1

  Usage
  get_usb_port [-t | -timeout (n seconds)] [-s | --silent]

  Arguments
  --timeout | -t : Timeout for plugging in the usb device default is 10 seconds
  --silent  | -s : Only output the result

EOF
}

while [ $# -gt 0 ]; do
  case "${1}" in
    --silent*|-s*) arg_silent=1 ;;
    --timeout*|-t*) shift; arg_timeout="${1}" ;;
    --help|-h) printhelp; exit 0 ;;
    *) >&2 printf "Error: Invalid argument\n"; exit 1 ;;
  esac
  shift
done

[[ $arg_timeout < 1 ]] && \
   { printf "Error: Invalid argument [-t --timeout] \n"; exit 1; }

[[ ! $arg_silent ]] && \
   printf "Plug in (or re-plugin) the usb device now...timeout in ${arg_timeout} seconds\n"

# test code
#UDEV="UDEV  [38.949135] add      /devices/platform/scb/usb1/1-1/1-1.3/1-1.3:1.0/ttyUSB1/tty/ttyUSB1 (tty)"
#udm_output=$(./timeout -t $arg_timeout sleep 2; echo "$UDEV" | \
#                grep -E '(^UDEV .*\[[0-9]*\.[0-9]*\] add )')

timeout=$(dirname ${BASH_SOURCE[0]})/timeout
#echo "TT:${timeout}"
udm_output=$("${timeout}" -t $arg_timeout udevadm monitor --subsystem-match=tty -u | \
               grep -E '(^UDEV .*\[[0-9]*\.[0-9]*\] add )')

if [[ -n "${TTY}" ]]; then
  udm_output="${udm_output##*'/'}" # return everythng after the last '/'
  tty="${udm_output% *}"    # trim ' (tty)' from the end
fi

if [[ -z $tty ]]; then
  [[ -z $arg_silent ]] && printf "No device detected"
else
  echo $tty
fi
