#!/bin/bash

# --------------------------------------------------------
# Finds and replaces multiline text in the string contents provided
# in STDIN. The search string can contain any characters.
# Arguments
# $1 (required): The multi-line string to find/replace
#  --break-on-first | -b : Exists when the first item is found or removed. 
#  --find-only      | -f : Find the text only. Returns the number of occurances. if break-on-first will return 1
#                          otherwise the source string is returned with the multiline strings removed. 
#  --trim-lines     | -t : Trims line feeds around the removed strings. (tries to leave one space)
#  --replacement-text | optional text to replace the exiting text
#  Input: Content via STDIN '< [filename]' or '<<< [string]' to supply the contents
#  Returns: The modified string or the number of matches depending on the options above
# --------------------------------------------------------

printhelp() {
  cat <<EOF
Searches for a multiline string in the stdin.

  Version 1.1

  Arguments:
  \$1 : the multiline string to find/replace
  --break-on-first   | -b : Exists when the first item is found or removed.
  --find-only        | -f : Find the text only. Returns the number of occurances. if break-on-first will return 1
                          otherwise the source string is returned with the multiline strings removed.
  --trim-lines       | -t : Trims line feeds around the removed strings. (tries to leave one space)
  --replacement-text | optional text to replace the exiting text
  Input: Content via STDIN '< [filename]' or '<<< [string]' to supply the contents
  Returns: The modified string or the number of matches depending on the options above
"
EOF
}

multiline_string_match() {

  if [[ "$1" != "--help" ]]; then

    if [[ -z "$1" ]]; then
      echo "no search string provided"
      exit 1
    fi

    IFS=$'\n' read -d '' -r -a pat_lines <<< "$1"
    shift

    local pat_len=${#pat_lines[@]}; local idx_pat=0
    local match_start=-1; local found=0
    local opt_break_on_first=0; local opt_find_only=0
    local opt_trim_lines=0
    local opt_replacement_text=
    local newline=$'\n'
    local output=
  fi

# process args
while [ $# -gt 0 ]; do
  case "$1" in
    --break-on-first*|-b*) opt_break_on_first=1 ;;
    --find-only*|-f*) opt_find_only=1 ;;
    --trim-lines*|-t*) opt_trim_lines=1 ;;
    --replacement-text*|-r*)
      if [[ "$1" != *=* ]]; then shift; fi # Value is next arg if no `=`
      opt_replacement_text="${1#*=}" ;;
    --help|-h) printhelp; exit 0 ;;
    *) >&2 printf "string-helpers.sh :Error: Invalid argument\n"; exit 1 ;;
  esac
  shift
done

########################################################

  # for debugging
  #for pline in "${pat_lines[@]}"; do echo "$idx_pat:$pline"; idx_pat+=1; done
  # idx_pat=0

  while IFS= read -r line; do

    if [[ "${pat_lines[$idx_pat]}" = "$line" ]] && \
      [[ $found = 0 || $opt_break_on_first != 1 ]]; then

      [[ $idx_pat = 0 ]] && match_start=${#output}

      idx_pat+=1
      if [[ $idx_pat = $pat_len ]]; then
        idx_pat=0
        found+=1
        if [[ $opt_find_only = 0 ]]; then
          if [[ $opt_trim_lines = 0 ]]; then
            output="${output:0:match_start}${opt_replacement_text}"
          else
            [[ "${output:(match_start-2):1}" == "$newline" ]] && match_start=$((match_start-1))

            output="${output:0:match_start}${opt_replacement_text}"
            IFS= read -r line
            if [[ -n "$line" ]]; then
              output+="${newline}$line"
            fi
          fi
        elif [[ $opt_break_on_first = 1 ]]; then
          break
        fi
        continue
      fi
    else
      idx_pat=0
    fi

    if [[ $opt_find_only = 0 ]]; then output+="${newline}$line"; fi
  done

  if [[ $opt_find_only = 0 ]] ; then
    echo "${output}"
  elif [[ $found > 0 ]]; then
    echo $found
  fi

}
