#!/bin/sh

source /data/opkg-helpers/opkg-common.sh
PACKAGE_NAME=$(basename "${0%.*}") #get file name without path

# Declare service in serial starter conf file
SERIAL_STARTER_CONFIG='/etc/venus/serial-starter.conf'
CONFIG='service relay       dbus-ne-shunt'
if ! grep -q "^$CONFIG$" "$SERIAL_STARTER_CONFIG"; then
  echo "$CONFIG" >> "$SERIAL_STARTER_CONFIG"
fi

add_package_name_to_custom_packages_file "${PACKAGE_NAME}"