#!/bin/sh

source /data/opkg-helpers/opkg-common.sh
PACKAGE_NAME=$(basename "${0%.*}") #get file name without path

# Remove service from serial starter conf file
SERIAL_STARTER_CONFIG='/etc/venus/serial-starter.conf'
CONFIG='service relay       dbus-relay-board'
if grep -q "^$CONFIG$" "$SERIAL_STARTER_CONFIG"; then
  sed -i "/^$CONFIG$/d" "$SERIAL_STARTER_CONFIG"
fi

remove_package_name_from_custom_packages_file "${PACKAGE_NAME}"

# Remove configuration files
rm -r /etc/dbus-relay-board
