// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_OpkgManager();
Q_GHS_KEEP_REFERENCE(qml_register_types_OpkgManager)

class OpkgManagerPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    OpkgManagerPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_OpkgManager;
        Q_UNUSED(registration)
    }
};



#include "OpkgManagerpluginplugin_OpkgManagerPlugin.moc"
