class dbus_constants:

	PRODUCT_NAME = "Inetbox"
	DBUS_PRODUCT_NAME="dbus_inetbox"
	CUSTOM_DEVICE_PAGE = "InetboxDevicePage"
	
	SERVICE_TYPE_TEMPERATURE="temperature"

	PRODUCT_ID = 0xD01A
	PRODUCT_VERSION = "0.02"
	FIRMWARE_VERSION = "0.02"
	HARDWARE_VERSION = "0.00"
 
	DEFAULT_DEVICE_INSTANCE = 817
