#!/usr/bin/env bash

PACKAGE_DEVICE_KEY="TestDevice"
PACKAGE_DEVICE_SERVICE_NAME="test-device-service"
PACKAGE_DEVICE_DISPLAY_NAME="Test Device"

PACKAGE_CUSTOM_OVERVIEW_PAGES=()
PACKAGE_DBUS_SETTINGS=

#PACKAGE_DBUS_SETTINGS_DEPRECATED="
#		{'path':'/Settings/OpkgManager/CustomMenus/PageSettingsDisplay/PageSettingsNeShuntSubMenu'}
#"

pre_install() {
	if [[ $PACKAGE_ACTION == "dev-install" ]]; then
		install_helper_add_custom_device
		exit 0
	fi
}
pre_remove() {
	if [[ "$PACKAGE_ACTION" == "dev-remove" ]]; then
  	echo "dev-install"
		install_helper_remove_custom_device
		exit 0
	fi
}

# shellcheck source=/data/dev/addons/opkg-manager/src/data/opkg-manager/source-common
source "${VE_ROOT_PATH:-}/data/opkg-manager/source-common"
addsource install-helper "$@"
