#!/bin/bash

# The Bash shell script executes a command with a time-out.
# Upon time-out expiration SIGTERM (15) is sent to the process. If the signal
# is blocked, then the subsequent SIGKILL (9) terminates it.
#
# Based on the Bash documentation example.

scriptName="${0##*/}"

opt_timeout=9  # Timeout.
opt_interval=1 # Interval between checks if the process is still alive.
opt_delay=1    # Delay between posting the SIGTERM signal and destroying the process by SIGKILL.

function printhelp() {
    cat <<EOF

Synopsis
    $scriptName [-t timeout] [-i interval] [-d delay] command
    Execute a command with a time-out.
    Upon time-out expiration SIGTERM (15) is sent to the process. If SIGTERM
    signal is blocked, then the subsequent SIGKILL (9) terminates it.

    [-t|--timeout] (optional)
        Number of seconds to wait for command completion.
        Default value: 10 seconds.

    [-i|--interval] (optional)
        Interval between checks if the process is still alive.
        Positive integer, default value: 1 seconds.

    [-d|--delay] (optional)
        Delay between posting the SIGTERM signal and destroying the
        process by SIGKILL. Default value: 1 seconds.

As of today, Bash does not support floating point arithmetic (sleep does),
therefore all delay/time values must be integers.
EOF
}

# process args
while [ $# -gt 0 ]; do
  case "$1" in
    --timeout*|-t*) shift; opt_timeout=$1 ;;
    --interval*|-i*) shift; opt_interval=$1 ;;
    --delay*|-d*) shift; opt_delay=$1 ;;
    --help|-h) printhelp ;exit 0 ;;
    -*)>&2 printf "Error: Invalid argument\n"; exit 1;;
    *) break;;
  esac
  shift
done

# $# should be at least 1 (the command to execute), however it may be strictly
# greater than 1 if the command itself has options.
if (($# == 0 || opt_interval <= 0)); then
  printhelp
  exit 1
fi

# execute the code in an inner process so that if we time out,
# we kill the outer process and we eat the `Terminated` message
# kill -0 PID validates the PID but does not KILL returns 0
# (process exists or 1 (process does not exist)

echo "o$BASHPID"

(
  outerBASHPID=$BASHPID
  (

    echo "z:$outerBASHPID"
    ((t = opt_timeout))
    while ((t > 0)); do
      sleep $opt_interval; ((t -= opt_interval));
      echo "t:$t"
      echo "o:$outerBASHPID"
      kill -0 $outerBASHPID
      r=$?
      echo "$r"
     if [[ $r = 1 ]]; then
        echo "exiting..."; exit 0
     fi
    done

    echo "killing..."
    # Be nice, post SIGTERM first.
    # The 'exit 0' below will be executed if any preceeding command fails.
    #pkill -s SIGTERM "test" 2>/dev/null && pgrep "test" || exit 0
    sleep $opt_delay
    echo "kill, kill"
    pp=$(pgrep "test")
    pkill --signal SIGKILL "test"
    echo "out:$pp"
    wait $pp
    echo "out"
  ) &

  echo "aaaaa"
  exec -a "test" sleep 20
  #$@

)

set +m

echo "bye"
