#!/usr/bin/env bash

# test-runner-ignore

# unreachable SC2329,SC2317
# shellcheck disable=SC2329,SC2317
# modified in subshell
# shellcheck disable=SC2031
# shellcheck disable=SC2086

set -o nounset

this_path="$(dirname "${BASH_SOURCE[0]}")"

#if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  #printf "\033c" # clear
#fi

echo "$this_path"
 
. "$this_path/../../../scripts/libs/test-lib"
. "$this_path/../src/data/opkg-helpers/libs/core-lib"
. "$this_path/../src/data/opkg-helpers/libs/log-lib"
. "$this_path/../src/data/opkg-helpers/libs/conf-lib"
. "$this_path/../src/data/opkg-helpers/serial-device-installer"

#src_code_path="${this_path}/../src/data/opkg-helpers"

this_dir_full="$(core_lib_realpath_nosymlinks "${this_path}")"
output_dir="${this_dir_full}/output"
assets_dir="${this_dir_full}/assets"
#src_code_path="$(core_lib_realpath_nosymlinks "${this_dir_full}/../src/data/opkg-helpers")"

clear_output() {
  mkdir -p "$output_dir"
  rm -fr "${output_dir:?}/"*
  #cp -r "${ASSETS_DIR}/"* "$OUTPUT_DIR/"
}
 
reset_assets() {
  clean_output

  #mkdir -p "${SERVICE_SERIAL_STARTER_PATH}"
  #mkdir -p "${SERVICE_PATH}"
  cp -r "${assets_dir}/serial-starter.rules" "${output_dir}/"
  cp -r "${assets_dir}/serial-starter.conf" "${output_dir}/"
  cp -r "${assets_dir}/installer.conf.test" "${output_dir}/"
}

scaffold_install_usb_serial_device() {
  push_log_indent
  install_usb_serial_device
  local -i r=$?
  pop_log_indent
  return "$r"
}

# shellcheck disable=SC2120
stage_files() {
  
  local args=("$@")
  (( ${#args[@]} == 0 )) && {
    args=("serial-device-installer.test1.conf" "serial-device-installer.test1.conf.schema")
  }

  clear_output
 
  for file in "${args[@]}"; do
    [ -f "${assets_dir}/${file}" ] || { assert_file_exists "$file" "stage_file not found" >&2; return 1; }
    cp "${assets_dir}/${file}" "${output_dir}/${file}" 
  done

  return 0
}  

#logging##############################
LOGLEVEL=$LOGLEVEL_TRACE
#LOGLEVEL=$LOGLEVEL_NONE
#LOGLEVEL=$LOGLEVEL_ERROR
LOG_DATE_TIME=
 
#testing#############################
EXIT_ON_FAILED_TEST=1
silent="--"

conf_file="${output_dir}/installer.conf"
test_SERVICE_NAME='dummy_service'
test_SERVICE_MAPPING_NAME="ve_${test_SERVICE_NAME}"
test_TTY='ttyUSB0'
test_SERIAL_STARTER_RULES_FILE="${output_dir}/serial-starter.rules"
test_SERIAL_STARTER_CONF_FILE="${output_dir}/serial-starter.conf"

# tests loading the serial-device-installer.conf.schema file
test_serial_device_installer_schema() {
 
  schema_file="$this_path/assets/serial-device-installer.test1.conf.schema"

  conf_lib_lint "$schema_file"
  assert_exitcode

}

# test loading from schema file fails when required vars are missing; conf file is also missing
test_load_with_schema_fails_missing_required() {
 
  stage_files "serial-device-installer.test1.conf.schema" # only copy schema
  
  conf_file="$output_dir/serial-device-installer.test1.conf"
  assert_file_not_exist "$conf_file" $silent
  assert_file_exists "${conf_file}.schema" $silent

  local stderr=
  exec 3>&1
  stderr="$(conf_lib_load_with_schema "$conf_file" 2>&1 1>&3)"
  assert_exitcode 1 "Missing Required Values"
  assert_eq "Missing required value for '\$SERVICE_NAME'" "${stderr}" "stderr correct"

  local var_set=false
  [[ -v "SERVICE_NAME" ]] && var_set=true
  assert_eq false "$var_set" "SERVICE_NAME is unset"
 
}
# test loading from schema file fails when required vars are missing; conf file is also missing
test_load_with_schema_succeeds_required_vars_provided() {
 
  stage_files "serial-device-installer.test1.conf.schema" # only copy schema
 
  conf_file="$output_dir/serial-device-installer.test1.conf"
  assert_file_not_exist "$conf_file" $silent
  assert_file_exists "${conf_file}.schema" $silent

  local ___SERVICE_NAME=$test_SERVICE_NAME

  conf_lib_load_with_schema "$conf_file"
  assert_exitcode 0 "Missing Required Values"
  assert_eq "$SERVICE_NAME" "$test_SERVICE_NAME"
  assert_empty "${SERVICE_MAPPING_NAME:-}" $silent
  assert_empty "${TTY-}" $silent
  assert_empty "$SERIAL_STARTER_RULE" $silent
  assert_not_empty "$SERVICE_PATH" $silent
  assert_not_empty "$SERIAL_STARTER_START_SERVICE_PATH" $silent
  assert_not_empty "$SERIAL_STARTER_RULES_FILE" $silent
  assert_not_empty "$SERIAL_STARTER_CONFIG_FILE" $silent
  assert_not_empty "$SERIAL_STARTER_CONFIG_TEXT_MATCH" $silent
  assert_not_empty "$SERIAL_STARTER_RULES_TEXT_MATCH" $silent
  assert_not_empty "$UDEVADM_PROPS" $silent
  assert_not_empty "$USE_UDEVADM_MONITOR" $silent
 }
 
# test loading defaults from schema file; required vars set
test_load_with_schema_filled_required_vars() {
  
  stage_files "serial-device-installer.test1.conf"
  
  __SERVICE_NAME="$test_SERVICE_NAME"
  conf_lib_load_with_schema "$conf_file"
  assert_exitcode 0 
  assert_eq "$SERVICE_NAME" "$test_SERVICE_NAME" $silent
}
 
# test loading defaults from schema file; conf file is missing; required vars set
test_load_with_schema_filled_required_vars() {

  stage_files

  conf_file="$output_dir/serial-device-installer.test1.conf"
  
  ___SERVICE_NAME="$test_SERVICE_NAME"
  conf_lib_load_with_schema "$conf_file"
  conf_lib_save_with_schema "$conf_file"
  assert_exitcode 0 
  assert_eq "$SERVICE_NAME" "$test_SERVICE_NAME" $silent
}

if [[ "${0:-}" == "$BASH_SOURCE" ]]; then
  #clear
  #test_load_with_schema_filled_required_vars
  #exit
  test_runner_all --summary "" #"^cur_test_*"
fi