#!/usr/bin/env bash

set -o nounset
 
EXIT_ON_FAILED_TEST=
TEST_INDENT=
TEST_RUNNER_ERROR_COUNT=0
TEST_RUNNER_SUCCESS_COUNT=0
TEST_RUNNER_SILENT=
 
__test_lib_pass_or_fail() {

  # result is always the first
  # comment is always the second
  local result=$1
  local comment="$2"
 
  shift 2 # remove result & comment
 
  if [[ -n "${comment}" ]]; then
    [[ $# -gt 0 ]] && comment="${comment//#1/\'${1}\'}"
    [[ $# -gt 1 ]] && comment="${comment//#2/\'${2}\'}"

    if [[ "${comment::2}" == "--" ]]; then
      if [[ $result == true ]]; then
        return 0 # return without printing
      fi
      comment="${comment:2:${#comment}}"
    fi
  fi  

  if [[ $result == true ]]; then
    TEST_RUNNER_SUCCESS_COUNT=$(( TEST_RUNNER_SUCCESS_COUNT+=1 ))
    # \u2714\ufe0f
    # \u2705'
    #success="PASSED"
    #echo -e "${TEST_INDENT}\033[32mPASSED\033[00m: $comment"
    (( ! TEST_RUNNER_SILENT )) && {
      printf '%s\033[32m\u2705\ufe0f - \033[00m%s\n' "${TEST_INDENT}" "${comment}"
    }
  else
    TEST_RUNNER_ERROR_COUNT=$(( TEST_RUNNER_ERROR_COUNT+=1 ))

    local lineNo="${BASH_LINENO[1]}"
    # u274c\ufe0f cross
    #echo -e "${TEST_INDENT}\033[31;1mFAILED (line:$lineNo)\033[00m: \e[9m$comment\e[0m"
    
    # (( ! TEST_RUNNER_SILENT )) && {
      printf '%s\033[31;1m\u274c\ufe0f (line:%s)\033[00m: %s\e[0m\n' "${TEST_INDENT}" "${lineNo}" "${comment}"
      for (( i=1; i <= "$#"; i++ )); do printf '%s%q\n' "${TEST_INDENT}" "${!i}"; done
    #}
    if [[ $EXIT_ON_FAILED_TEST  ]]; then
      exit 255
    fi
  fi
  # some true results are formed from fails (file not exist etc..)
  # so make sure we an exit code based on the result
  #[[ $result ]] && return 0 
  return 0
}
 
__set_comment() {
  local -n _comment="$1" 
  if [[ -z "$_comment" || "$_comment" == "--" ]]; then
    _comment+="$2"
  fi
}

###################################
# Tests if a file exists
# Arguments:
#   $1 file name
#   $2 optional - comment; default; "File exists"
#   $3 optional - retry count; default 1
###################################
test_file_exists() {
  local result=false
  local comment="${2:-}"
  local -i retry_count="${3:-1}"

  __set_comment comment "File exists"
  while (( retry_count > 0)); do
    [[ -f "${1}" ]] && { result=true; break; }
    (( retry_count-=1 ))
    sleep 0.25
  done

  __test_lib_pass_or_fail $result "$comment" "file:$1"

}

###################################
# Tests if a file does not exist
# Arguments:
#   $1 file name
#   $2 comment
###################################
test_file_not_exist() {
  local result=false
  local comment="${2:-}"
  __set_comment comment "File does not exist"
  [[ -f "${1}" ]] || result=true
  __test_lib_pass_or_fail $result "$comment" "file:$1"
}

###################################
# Tests if a directory exists
# Arguments:
#   $1 directory path
#   $2 comment
###################################
test_dir_exists() {
  local result=false
  local comment="${2:-}"
  __set_comment comment "Path exists"
  [[ -d "${1}" ]] && result=true
  __test_lib_pass_or_fail $result "$comment" "path:$1"
}

###################################
# Tests if a directory does not exist
# Arguments:
#   $1 directory path
#   $2 comment
###################################
test_dir_not_exist() {
  local result=false
  local comment="${2:-}"
  __set_comment comment "Path does not exist"
  [[ -d "${1}" ]] || result=true
  __test_lib_pass_or_fail $result "$comment" "path:$1"
}

###################################
# Tests if 2 values are equal
# Arguments:
#   $1 value1
#   $2 value2
#   $3 comment
###################################
test_eq() { 
  local result=false
  local comment="${3:-}"
  __set_comment comment "Values are equal"
  [[ "${1}" == "${2}" ]] && result=true
  __test_lib_pass_or_fail $result "$comment" "value 1:$1" "value 2:$2"
 }
 
 ###################################
# Tests if value1 is greater than value 2
# Arguments:
#   $1 value1
#   $2 value1
#   $3 comment
###################################
test_gt() { 
  local result=false
  local comment="${3:-}"
  __set_comment comment "Value1 is greater than Value2"
  (( "${1}" > "${2}" )) && result=true
  __test_lib_pass_or_fail $result "$comment" "value 1:$1" "value 2:$2"
 }

###################################
# Tests if value1 is less than value 2
# Arguments:
#   $1 value1
#   $2 value1
#   $3 comment
###################################
test_lt() { 
  local result=false
  local comment="${3:-}"
  __set_comment comment "Value1 is less than Value2"
  (( "${1}" < "${2}" )) && result=true
  __test_lib_pass_or_fail $result "$comment" "value 1:$1" "value 2:$2"
 }

###################################
# Tests if value1 is between value 2 and value 3
# Arguments:
#   $1 value1
#   $2 value2
#   $3 value3
#   $4 comment
###################################
test_between() { 

  if (( "${2}" >= "${3}"  )); then
    echo "value1 must be greater than value 2" &>2; 
    return 0
  fi
 
  local result=false
  local comment="${4:-}"
  __set_comment comment "Value1 is less than Value2"
  (( "${1}" >= "${2}" )) && (( "${1}" <= "${3}" )) && result=true
  __test_lib_pass_or_fail $result "$comment" "value 1:$1" "value 2:$2" "value 3:$3"
 }

###################################
# Tests if 2 values are not equal
# Arguments:
#   $1 value1
#   $2 value2
#   $3 comment
###################################
test_not_eq() {
  local result=false
  local comment="${3:-}"
  __set_comment comment "Values are not equal"
  [[ "${1}" != "${2}" ]] && result=true
  __test_lib_pass_or_fail $result "$comment" "value 1:$1" "value 2:$2"
 }
 
###################################
# Tests if the value is empty
# Arguments:
#   $1 value
#   $2 comment
###################################
test_empty() {
  local result=false
  local comment="${2:-}"
  __set_comment comment "Value is empty"
  [[ -z "${1}" ]] && result=true
  __test_lib_pass_or_fail $result "$comment" "value:$1"
}

###################################
# Logs the result of an external test
# Arguments:
#   $1 result
#   $2 comment
#   $3 any args
###################################
test_result() {
  local result=false
  local comment="${2:-}"
  [[ ${1} ]] && result=true # normalize the results to true/false
  __set_comment comment "Test Result=${1}"
  shift 2 # for args
  __test_lib_pass_or_fail $result "$comment" "${@}"
}

###################################
# Tests if the value is not empty
# Arguments:
#   $1 value
#   $2 comment
###################################
test_not_empty() { 
  local result=false
  local comment="${2:-}"
  __set_comment comment "Value is not empty"
  [[ -n "${1}" ]] && result=true
  __test_lib_pass_or_fail $result "$comment" "value:$1"
 }
 
###################################
# Tests if the exit code equals
# Arguments:
#   $1 - required; exit code to match
#   $2 - optional; comment
# this method must be placed directly
# after the command to check as it
# uses "$?"
###################################
test_exitcode() {
  exitcode=$?
  local result=false
  local comment="${2:-}"
  local expected=${1:-0}
  __set_comment comment "Exit code is valid"
  (( exitcode == expected )) && result=true
  __test_lib_pass_or_fail $result "$comment" "expected:$expected" "recieved:$exitcode"
}

###################################
# Tests if the exit code does not equal
# Arguments:
#   $1 - required; exit code to not match
#   $2 - optional; comment
# this method must be placed directly
# after the command to check as it
# uses "$?"
###################################
test_exitcode_not() {
  exitcode=$?
  local result=false
  local comment="${2:-}"
  local arg1 arg2
  #if [[ ! $comment ]]; then
    arg1="not expecting:$1"; arg2="recieved:$exitcode"
  #else
  #  arg1="$1"; arg2="$exitcode"
  #fi
  __set_comment comment "Exit code is valid" 
  (( exitcode != ${1} )) && result=true
  __test_lib_pass_or_fail $result "$comment" "$arg1" "$arg2"
}

###################################
# Tests if a file contains a string
# Arguments:
#   $1 - required; the file to check
#   $2 - required; the string value to find
#   $3 - optional comment
###################################
test_file_contains() {
  local result=false
  local file="${1}"
  local match="${2}"
  local comment="${3:-}"
  __set_comment comment "File contains"
  # don't try to match if match string is empty
  [[ -n "${match}" ]] && [[ "$(<"${file}")" = *"${match}"* ]] && result=true
  __test_lib_pass_or_fail $result "$comment" "file:$file" "match:$match"
}

###################################
# Tests if a file does not contain a string
# Arguments:
#   $1 the file to check
#   $2 the string value to find
#   $3 comment
###################################
test_file_not_contain() { 
  local result=false
  local file="${1}"
  local match="${2}"
  local comment="${3:-}"
  __set_comment comment "File does not contain"
  # don't try to match if match string is empty
  [[ -n "${match}" ]] && [[ "$(<"${file}")" = *"${match}"* ]] || result=true
  __test_lib_pass_or_fail $result "$comment" "file:$file" "match:$match"
}
 
###################################
# Runs an array of test functions
# Arguments:
#   $1 an array of functions to run
#
# Each function is run in its own
# issolated process '(...)''
###################################
test_runner() {
  local -i summary=0
   [[ "${1:-}" == "--summary" ]] && { shift; summary=1; }

  local -n _tests="$1"
  local -n _comments="$2"
  local -i i=0
  local error_count=0
  local success_count=0
  local tmpFile="/tmp/test-runner-${BASHPID}"  
  local -i result=
  local saved_TEST_RUNNER_SILENT=$TEST_RUNNER_SILENT
  local style=
  local output=
  local icon=

  if (( summary )); then
    TEST_RUNNER_SILENT=1
  fi

  # shellcheck disable=SC2329,SC2317
  cleanup() { 
    TEST_RUNNER_SILENT=${saved_TEST_RUNNER_SILENT:-}
    local tmpFile="/tmp/test-runner-${BASHPID}"
    if [[ -f "$tmpFile" ]]; then
      rm "$tmpFile" 
    fi
  }
  
  set_print_style() {
    if (( result != 0 )) && (( result != 255 )); then
      output="---Syntax error---"$'\n'"$output"$'\n'
      style='\033[1;35m'
      icon=
    elif (( TEST_RUNNER_ERROR_COUNT > 0 )); then
      style='\033[31;1m'
      icon='\u274c\ufe0f'
    elif (( TEST_RUNNER_SUCCESS_COUNT > 0 )); then
      style='\033[32m'
      icon='\u2705\ufe0f'
    else
      style='\033[1;37m'
      icon=
    fi
  }

  # shellcheck disable=SC2329,SC2317
  exit_test() {
    echo -e "TEST_RUNNER_SUCCESS_COUNT=$TEST_RUNNER_SUCCESS_COUNT\
    TEST_RUNNER_ERROR_COUNT=$TEST_RUNNER_ERROR_COUNT\n" >"$tmpFile"
  }

  box_string() {
    local string="$1"
    local -i stringLen=${#string}
    (( stringLen += 2 )) # +2 for spaces
    [[ -n $icon ]] && (( stringLen += 2 ))
    printf -v "horz" '%.s─' $(seq 1 $stringLen) # create horizontal line in var horz
    printf "${style}"'\u250c%s\u2510\n\u2502'"${icon}"' %s \u2502\n\u2514%s\u2518\n\e[m' "$horz" "$string" $horz
  }

  trap 'cleanup' EXIT

  for i in "${!_tests[@]}"; do
    TEST_RUNNER_ERROR_COUNT=0
    TEST_RUNNER_SUCCESS_COUNT=0
 
    output=$(
      trap "exit_test" EXIT
      ${_tests[$i]} 2>&1 
    ) 
    result=$?
     
    # shellcheck disable=SC1090
    if [[ -f "$tmpFile" ]]; then
       
      source "$tmpFile"
      success_count=$(( success_count+=TEST_RUNNER_SUCCESS_COUNT ))
      error_count=$(( error_count+=TEST_RUNNER_ERROR_COUNT ))

      rm -f "$tmpFile"
    fi
  
    set_print_style
    printf "${style}${icon}"' %s) '\''%s'\''\n\e[0m' "$(( i+1 ))" "${_comments[$i]}" 
    
    [[ -n "$output" ]] && printf "${style}"'%s\n\e[0m' "$output"

    if (( result != 0 )) && [[ $EXIT_ON_FAILED_TEST  ]]; then
      break
    fi
  done
 
  box_string "Tests completed: ${success_count} succeeded; ${error_count} failed"
   
  TEST_RUNNER_ERROR_COUNT=0
  TEST_RUNNER_SUCCESS_COUNT=0

  if (( result != 0 )) && [[ $EXIT_ON_FAILED_TEST  ]]; then
    exit 1
  fi

}

###################################
# Gets an array of public test functions
# from a file and then executes each
# function in a separate process
# Arguments:
#   $1 - optional; pass --summary, used to display 
#      a summary of the tests rather than showing 
#      each result
#   $1 - required; The file containing the 
#        tests to run
#   $2 - optional; Filters the name of the test
#        The default filter is "^test_*"
# Each function is run in its own
# isolated process '(...)''
###################################
test_runner_all() {

  local -a summary=()
  [[ "$1" == "--summary" ]] && { shift; summary=(--summary); }
 
  local file="${1:-${BASH_SOURCE[1]}}"
  local filter="${2:-^test_.*}"
 
  [[ -f "$file" ]] || { echo "file not found: $file" >&2; return 1; }
 
  # shellcheck disable=SC2034
  local -a tests comments
 
  __get_public_functions "$file" "$filter" tests comments

  #echo "testrunner test func count: ${#tests[@]}"  
  #for i in "${!tests[@]}"; do   
  #  echo "testrunner test func: ${tests[i]}"
  #done
  #tests=("test1" "test2")
  #comments=("comment1" "comment2")
  test_runner "${summary[@]}" tests comments 
 
}

###################################
# test runner for a complete set of 
# tests in a file
# Arguments:
#   $1 - optional; pass --summary, used to display 
#      a summary of the tests rather than showing 
#      each result
#   $1 - required The file to load using the source command
#   $2 - optional bash regx filter used filter the
#      functions names
# Notes:
# The source file is loaded into a
# separate process before calling
# test_runner_all to run all the tests in the file.
###################################
 
test_runner_on_source_file() {
 
  (
      local summary=()
      [[ "${1}" == "--summary" ]] && { shift; summary=("--summary"); }
      local src="${1}"
      local filter="${2:-}"
 
 
    if head -n 10 "$src" | grep -iq "# test-runner-ignore"; then
      echo "file: $1"
      echo "test-runner:file ignored: file contains # test-runner-ignore tag" >&2
      return 0;
    fi
 
    #shellcheck disable=SC1090
    source "$src"
 
    printf '\e[48;5;25m\n%s\n\e[0m\e[K' "${src##*/}" #"$spaces"

    test_runner_all "${summary[@]}" "${src}" "${filter}"
  )
}

__get_public_functions() {
  local file="$1"
  local filter="$2"
  local -n _names="$3"
  local -n _comments="$4"

  _names=()
  _comments=()

  [[ -f "$file" ]] || return 1

  local last_comment=""

  while IFS= read -r line; do
    # Capture single comment line
    if [[ "$line" =~ ^[[:space:]]*#[[:space:]]*(.*)$ ]]; then
      last_comment="${BASH_REMATCH[1]}"
      continue
    fi

    # Reset comment on blank or non-comment, non-function line
    [[ "$line" =~ ^[[:space:]]*$ ]] && continue
    [[ ! "$line" =~ ^[[:space:]]*(function[[:space:]]+)?[a-zA-Z_] ]] && last_comment=""

      # Match function definitions
    if [[ "$line" =~ ^[[:space:]]*(function[[:space:]]+)?([a-zA-Z_][a-zA-Z0-9_]*)[[:space:]]*(\(\))?[[:space:]]*\{ ]]; then
      local fn="${BASH_REMATCH[2]}"

      # Skip private functions
      [[ "$fn" == _* ]] && last_comment="" && continue

      # Optional filter
      
      [[ -n "$filter" && ! "$fn" =~ $filter ]] && last_comment="" && continue
  
      _names+=("$fn")
      _comments+=("$last_comment")
      last_comment=""
    fi
  done < "$file"
 
}
 